### ISSUE TITLE
Performance Issue: Provide option to disable antialiasing

### ISSUE THREAD

**Issue by Eerey** [rive-app/rive-flutter#100]
First of all, i really enjoy the new editor you provide. Works like a charm.
However, it seems like the feature to turn off `antialiasing` is not provided yet. In flare, the feature is already open to use: https://github.com/2d-inc/Flare-Flutter/issues/133

**First question**
Can you provide the feature to easily turn antialiasing off/on for rive?

**Second question**
I want to use multiple Rive Widgets / multiple Rive Artboards.
Should i use multiple Rive Widgets or should i try to integrate multiple Artboards into... one Artboard? I have multiple files for each Artboard.
My goal is to use (1) a Background Layer (Rive Widget) that is animated and two (2)+(3) other Rive Widgets that are rendered on top of the Background Layer. However, the performance is bad, it only runs ~20 fps. I noticed that opacity is resource-heavy, so I tried to only work with translations, scalings, rotations and bone animations.
Here are the results (yes, it's debug, but in Profile and Release the performance is - relatively speaking - the same.

0 Rive Widgets:
![image](https://user-images.githubusercontent.com/7249645/118381338-41739280-b5ea-11eb-84f7-ca1864a6ca7e.png)
1 Rive Widget:
![image](https://user-images.githubusercontent.com/7249645/118381324-2143d380-b5ea-11eb-9903-966a5017fb8a.png)
3 Rive Widgets:
![image](https://user-images.githubusercontent.com/7249645/118381352-5ea86100-b5ea-11eb-8844-8d85b5446938.png)

Thanks for the great plugin.
Looking forward to your response.

**Comment by luigi-rosso** [comment]
Hi @Eerey, turning off anti-aliasing definitely helps on certain devices, what device are you testing on? We'll add this feature to our roadmap!
