### ISSUE TITLE
Contents of old .flr file persisting after deletion in Flutter project

### ISSUE THREAD

**Issue by jhh1988** [rive-app/rive-flutter#11]
I created an animation in Rive, found [here](https://rive.app/a/turtleIsland/files/flare/search), and i exported it into my flutter project. I then edited the Rive animation (changed a color), and then re-exported it and added it into my flutter project. I then deleted the old .flr file that was there, and changed the name of the new .flr file to be the same name of the one I just deleted. 

The issue is that part of the object I created in Rive still has an element in it that is the same color in flutter as the deleted .flr file. 

Let me know if you need any more info.

**Comment by jhh1988** [comment]
Closing.... I had accidentally set a new color as part of the animation occurring at around 6 seconds, which was impossible for me to see when the animation time frame in zoomed in far enough. Would be helpful to show an icon for each animation, even if it is out of the time frame in which the user is currently focused.

**Comment by mjohnsullivan** [comment]
Thanks for the feedback! (fyi: @neurowave).
