### ISSUE TITLE
Nested Animation in Rive

### ISSUE THREAD

**Issue by llorenzo** [rive-app/rive-flutter#112]
I need a terrain map with the same small animation placed many times over the map. The terrain map itself is animated, moving along, zoomed in and out. How to not redo the same small animation many times, placed on the map? Also I need to trigger each small animation on press.
Any Ideas?

**Comment by mjohnsullivan** [comment]
We recently added in instancing on artboards (`artboard.instance()`), so you can instance the same artboard multiple times and not have to load an asset for each one.

This example trivially uses one: https://github.com/rive-app/rive-flutter/blob/master/example/lib/example_animation.dart

but we'll be documenting and showing a better example shortly.

**Comment by luigi-rosso** [comment]
Nested Artboards have landed in the flutter runtime, support will shortly be available in the editor too!

**Comment by cm-phm** [comment]
The nested artboard animations are working fine in flutter but there is an issue using them in a State Machine which is I suppose related with StateMachineController

**Comment by floki2020** [comment]
> Nested Artboards have landed in the flutter runtime, support will shortly be available in the editor too!

How can i get the Nested Artboarts? Use the artborad's  property activeNestedArtboards? Thanks ...
