### ISSUE TITLE
lineargradient bug

### ISSUE THREAD

**Issue by gulmensedat** [rive-app/rive-flutter#116]
When I use LinearGradient, the LinearGradient methods in the package and flutter library conflict and give an error. It needs to be fixed.

**Comment by luigi-rosso** [comment]
You can import the rive linear gradient with an "as rive" at the end of the import statement. Then you can use it as rive.LinearGradient to disambiguate with Flutter's one. See solution "b" here for more details https://coflutter.com/dart-flutter-how-to-solve-naming-conflict-or-ambiguous-import/ 

This is what Flutter does internally when it imports 'dart:ui' as ui to disambiguate internal class names.
