### ISSUE TITLE
Error: The method 'Shape.draw' has fewer positional arguments than those of overridden method 'Drawable.draw'

### ISSUE THREAD

**Issue by gbpadial** [rive-app/rive-flutter#119]
Just to address you an error I've found today while trying to flutter run my project:

.../rive-0.7.15/lib/src/rive_core/shapes/shape.dart:163:8: Error: The method 'Shape.draw' has fewer positional arguments than those of overridden method 'Drawable.draw'.
  **void draw(ui.Canvas canvas) {**

I got it to work by check the abstract class method, and them changing the signature of shape.dart, like this:
void draw(Canvas canvas, **[bool antialias = true]**);

Tnks!

**Comment by gabrielginter** [comment]
This error is happening to me as well with Flutter 2.2.1 (Stable channel)

Downgrading is the easiest and safest solution I would say

> I got it to work by check the abstract class method, and them changing the signature of shape.dart, like this:
> void draw(Canvas canvas, **[bool antialias = true]**);

I would recommend against modifying package classes, but it does solve the issue.

Cheers

**Comment by alloza95** [comment]
I get the same issue!

**Comment by mjohnsullivan** [comment]
Working on a fix for this now.

**Comment by mjohnsullivan** [comment]
0.7.16 has just been released to pub.
