### ISSUE TITLE
Issues with the web editor

### ISSUE THREAD

**Issue by normancarcamo** [rive-app/rive-flutter#12]
Hi there, thanks for the amazing job you are making in the editor, just want to point out that I have seen some issues while I'm using the editor.

1. The following image shows that sometimes the controls aren't visibles, unless I close the tab or if it's reloaded:

<img width="1440" alt="0" src="https://user-images.githubusercontent.com/2402579/93022054-fc531880-f5a3-11ea-861b-86fb0a427710.png">

I haven't tried yet to refresh the cache of my browser, but hope you can see that issue and may suggest me something to do here.

2. Another thing that I find it a bit annoying is the fact that a shape doesn't always saves the state when the file/tab/session is closed, some animations also don't save the state (maybe for the same reason?):

If I set a color like `#CCCCCC` for both, the stroke & the fill:
![1](https://user-images.githubusercontent.com/2402579/93022086-302e3e00-f5a4-11ea-9026-8e393579f9f0.png)

Then, if I set it's opacity to 0:
![2](https://user-images.githubusercontent.com/2402579/93022088-33c1c500-f5a4-11ea-91fe-af7f2c7b7076.png)

And I save the changes:
![3](https://user-images.githubusercontent.com/2402579/93022090-345a5b80-f5a4-11ea-8be6-4cd8aa39f024.png)

I reopen the file after the tab was closed:
![4](https://user-images.githubusercontent.com/2402579/93022091-345a5b80-f5a4-11ea-8a6c-933341f007e4.png)

It's supposed to be with an opacity of 0, but it gets ignored:
<img width="1440" alt="5" src="https://user-images.githubusercontent.com/2402579/93022219-60c2a780-f5a5-11ea-8cfa-1ad4cfbbfb88.png">

**Comment by umberto-sonnino** [comment]
Thanks for the detailed report, we're going to look into this in the near future!
This is the issue tracker for rive-flutter, that is the runtime for the upcoming version of Rive, for which you can signup [over here](https://beta.rive.app/)!

We currently keep track of Rive issues [in this repo instead](https://github.com/2d-inc/support/issues), would you mind opening the issue over there?
