### ISSUE TITLE
state machine not triggered on deployment

### ISSUE THREAD

**Issue by meniMaatuf** [rive-app/rive-flutter#127]
i'm using rive: ^0.7.16

and when i'm export apk with:
```flutter build apk --release```
and install the apk on real device
i'm see only the first animation works and when im turn on the trigger with:
```_trigger = _controller.findInput('trigger1');```
```_trigger.value = true;```

it's not works and im not see the next animation

any solution?

**Comment by mjohnsullivan** [comment]
Can you share your Rive file with us so we can take a look?

**Comment by meniMaatuf** [comment]
> Can you share your Rive file with us so we can take a look?

sure, this is a screenshot of my state machine on rive.app:

<img width="1440" alt="Screen Shot 2021-06-16 at 10 11 17" src="https://user-images.githubusercontent.com/25525536/122174451-6a0dd700-ce8b-11eb-9f02-86152d89aafd.png">

and this is how i use them in my code:

<img width="558" alt="Screen Shot 2021-06-16 at 10 14 28" src="https://user-images.githubusercontent.com/25525536/122174770-ab05eb80-ce8b-11eb-94aa-bf4dfb4a11b6.png">

and this is how i change the trigger input: 
```
_listeningInput.value = true;
_talkingInput.value = false;
```

when i'm run the app locally in android studio it's work fine.
but, when i'm building apk file and installing them in real device, it's stuck on first animation

**Comment by meniMaatuf** [comment]
@mjohnsullivan any idea?

**Comment by mjohnsullivan** [comment]
I can't see anything obvious from the code snippet you shared. I'd need to see the actual Rive file you're experiencing the issue with to dig further. If you're willing to share that, I can take a look.

**Comment by meniMaatuf** [comment]
here is the file
[start_button.riv.zip](https://github.com/rive-app/rive-flutter/files/6681878/start_button.riv.zip)

hopefully you can help me

**Comment by mjohnsullivan** [comment]
Taking a look at your file @meniMaatuf. Can you drop me an email at matt <at> rive <dot> app and we can work through it?

**Comment by meniMaatuf** [comment]
i'm sending to this email address: matt@rive.app rite right?

**Comment by mjohnsullivan** [comment]
Troubleshooting elsewhere.
