### ISSUE TITLE
Adjust some parameters of the animation from the application

### ISSUE THREAD

**Issue by kormoczi** [rive-app/rive-flutter#128]
Hi,

I would like to implement something similar to the old riveTeddyExample (which is Flare based) with the new Rive.
I would like to move some objects from code, like when the eyes of the bear follows the text input location in the above mentioned example.
How I can achieve this? What shall I specify in the riv file, what I should implement in the controller?
(I think this was called constraints in the old Rive...)

Thanks!

**Comment by mjohnsullivan** [comment]
The Teddy example made use of constraints, which we don't yet have (but are planned) in Rive.

However, state machine inputs can be used to achieve some of the same effects.

We've updated the Teddy example to show how this would work with a state machine: https://rive.app/community/520-990-teddy-login-screen/
