### ISSUE TITLE
where is OnShotAnimation class 

### ISSUE THREAD

**Issue by saviourdog** [rive-app/rive-flutter#129]
i cannot find it

**Comment by aspiiire** [comment]
I had the same issue, it is a typo, should be OneShotAnimation and not OnShot...

**Comment by Floul** [comment]
> I had the same issue, it is a typo, should be OneShotAnimation and not OnShot...

I can't find OneShotAnimation neither. Can you?

**Comment by mjohnsullivan** [comment]
Yeah, I misnamed that and fixed it in the latest release; are you still seeing it misnamed in Rive 0.7.18?

**Comment by mjohnsullivan** [comment]
Tested 0.7.19 release; OneShotAnimation is now correctly named.
