### ISSUE TITLE
Your examples should 'simply work'

### ISSUE THREAD

**Issue by 3SCadmin** [rive-app/rive-flutter#132]
Hi,

This is far from the only flutter project with this problem:   Your example code should be up to date and work.
No tweaking, no debugging, any noob who discovered your widget should be able to cut-n-paste your examples and not see red squiggly lines, or obscure error messages.

Today, out of the box: Only the first Quick Start example runs, the other 3 give errors.

**Comment by tsinis** [comment]
Hey @3SCadmin,

Sorry to say, but I don't think you're quite correct. Rive 2 is clearly in development right now and is being polished by the guys from the Rive team, every day. What's the point of that message? I believe, the product is not in its final phase and I'm more than confident that when it gets close to the final stage we will see some actual and neat examples with tutorials, for those who just want to start working with this great tool. If you really want to help with keeping the examples up to date—why don't you just send a PR with these example fixes, you have written about? As far as I can see, the team's priorities right now are in [Roadmap](https://feedback.rive.app/roadmap), so they can roll out the project to release asap...

**Comment by 3SCadmin** [comment]
>>What's the point of that message?
I'm pointing out that 3 of the 4 examples on pub.dev currently don't work.
It would take a minimal amount of effort for the rive.app team to maintain the example code, so that it works with the latest version of flutter as well as the latest version of their package.

Not all flutter packages are well maintained.  Non-working examples are usually not a good sign.

They appear to be a business trying to build a userbase around their product.
I figure it's in their best interest to make a good first impression.

**Comment by luigi-rosso** [comment]
Thanks for the feedback. This must be an issue with some of our recent api changes as they were all working before then. We'll get them fixed up soon.

**Comment by luigi-rosso** [comment]
Could you clarify which examples aren't working? I ran through all the examples included in the example folder and they function as expected:
![image](https://user-images.githubusercontent.com/454182/122659075-8e3a1400-d128-11eb-9893-8472bb1f25a8.png)

The other potential problem I see is that we didn't rev the minor version with the latest api changes, so there are some changes that are breaking which could be causing problems with semantic vesioning. The changes are documented in the [changelog](https://pub.dev/packages/rive/changelog). Make sure you're pubspec references ^0.7.19 and run pub get again. We'll make sure to rev the version correctly next time.

**Comment by 3SCadmin** [comment]
**Could you clarify which examples aren't working?**

on the Readme tab you have 3x examples.

First one works, cut-n-paste
Second one I never got to work
Third one, I got to run after fixing a typo and adding a main() function

On the example tab:  
There is a main.dart with a helpful 'copy-to-clipboard' icon.
But that doesn't work, instead you need to click on the link, navigate down 3 directories and git clone that project.
Now you have a working flutter project in the example sub-folder!

My point is:
It should be obvious to first-time visitors what they need to do.  
You want the first impression to be: Damn that's cool   , not:    It's broken!  How broken?  Can I fix it?

**Comment by luigi-rosso** [comment]
Oh, I see you're copying the example code directly from pub.dev. We'd meant those to be more reference than complete examples, but I see how that's confusing (and doesn't save that much in terms of brevity). 

It's fixed now, please let me know if you run into further issues, and thanks again for bringing it up. It'll definitely help others who are trying to do the same.

**Comment by 3SCadmin** [comment]
Excellent, thank you for addressing this.
