### ISSUE TITLE
How does FLR convert riv? I want to use the Teddy example. Can I update it

### ISSUE THREAD

**Issue by kuangmo123** [rive-app/rive-flutter#133]
How does FLR convert riv? I want to use the Teddy example. Can I update it

**Comment by luigi-rosso** [comment]
We have a converter for flr2d (Flare Project files which can be exported for backup from the old site at https://flare.rive.app/). You can drag and drop those into Rive. Note that these are .flr2d (project/backup) not .flr (runtime export) files.

The Teddy example from Flare uses some constraints which are not yet available in Rive so not everything will convert. @JcToon has created a new example in Rive which shows how to achieve something similar with the new features, but it's not available yet. We'll be posting it to the community soon. I'll keep this issue open and update when it's available!

**Comment by mjohnsullivan** [comment]
Updated Teedy example is here: https://rive.app/community/520-990-teddy-login-screen/
