### ISSUE TITLE
hi,i want to play only once,it awalys loop

### ISSUE THREAD

**Issue by saviourdog** [rive-app/rive-flutter#135]
this is my few code
![image](https://user-images.githubusercontent.com/22761043/123534052-b939ee80-d74c-11eb-9905-540100592143.png)

**Comment by luigi-rosso** [comment]
Hi @saviourdog, the easiest way to do this is by re-exporting the animation from Rive with no looping. rive-flutter respects the animation's settings set by the artists in Rive.

You can change the looping behavior to "One Shot" in this dropdown when in animate mode:
![Screen Shot 2021-06-28 at 4 44 06 PM](https://user-images.githubusercontent.com/454182/123716700-1d81ae80-d830-11eb-85f1-643f44770aba.png)

**Comment by saviourdog** [comment]
ok,thank you anyway
