### ISSUE TITLE
can rive load asset in package dependency? (plugin)

### ISSUE THREAD

**Issue by hamberluo** [rive-app/rive-flutter#142]

**Comment by luigi-rosso** [comment]
Hi @hamberluo, please follow our issue posting guidelines for future reports. 

Rive uses Flutter's rootBundle.load when loading a local asset via [RiveFile.asset](https://github.com/rive-app/rive-flutter/blob/61e83f31848aeea7abdc484a095b3fbe746f5b55/lib/src/rive_file.dart#L225-L228) or [RiveAnimation.asset](https://github.com/rive-app/rive-flutter/blob/61e83f31848aeea7abdc484a095b3fbe746f5b55/lib/src/widgets/rive_animation.dart#L53-L54). rootBundle.load can find assets from other packages if you prepend the name with ```packages/package_name```. 

More details in plenty of Flutter specific issues:
https://github.com/invertase/melos/issues/133
https://github.com/flutter/flutter/issues/65921
