### ISSUE TITLE
Reset unexpected behaviour

### ISSUE THREAD

**Issue by tantzygames** [rive-app/rive-flutter#144]
I had another issue along the way with my play button #143 

As described I need to hold the last frame of one shot animations, and so I reset the animation before playing. I discovered this only resets the keyframes that exist in that animation, leaving any un-reset states from other animations. I understand this is desired behaviour in many circumstances when mixing animations, but in this case I wanted reset to act in the same way as the Rive editor - reset to first keyframes or the default state if keyframes don't exist.

To accommodate this I had to set keyframes for every animated element in every animation which was quite tedious.

Perhaps there could be an option to reset all which resets to first keyframes or the default state if keyframes don't exist in that animation?

**Comment by HayesGordon** [comment]
Going to close this owing to the age of the Github issue. A lot more features and API have been introduced in both the editor and runtime.

Please feel free to reopen, or create a separate issue
