### ISSUE TITLE
Expose runtime major/minor version

### ISSUE THREAD

**Issue by IchordeDionysos** [rive-app/rive-flutter#15]
To know exactly the current installed version of the Rive package is, it would be helpful to expose this file:
https://github.com/rive-app/rive-flutter/blob/master/lib/src/rive_core/runtime/runtime_header.dart#L7

Or at least the runtime's major/minor version publicly.

This helps us to decide which version of the files that can be loaded from the network.
Currently, we have to maintain a separate variable of exactly these two [variables](https://github.com/rive-app/rive-flutter/blob/master/lib/src/rive_core/runtime/runtime_header.dart#L8-L9) in our codebase and keep them up-to-date every time we update the rive package.

So getting them via `RuntimeHeader.majorVersion` and `RuntimeHeader.minorVersion` would be very helpful.

**Comment by luigi-rosso** [comment]
Hi @IchordeDionysos! You can now get these as follows:

This will provide you with the version of the runtime itself:
```dart
print('Runtime version: ${riveVersion.major}.${riveVersion.minor}');
```

This will provide you with the version of a loaded file:
```dart
var file = RiveFile();
// Load the RiveFile from the binary data.
var success = file.import(data);
if (success) {
  print('File version: ${file.header.version.major}.${file.header.version.minor}');
}
```
