### ISSUE TITLE
App perfectly works on web, but for android gives exception: can't load asset 

### ISSUE THREAD

**Issue by nzxcvbnm** [rive-app/rive-flutter#154]
I need a raw object, because artboard/ background is not good for my project. What to do? 
Also, this package is way more complex than flare

**Edit**: application on web works, but the same app when trying on android gives error: can't load asset. 

[https://i.stack.imgur.com/oudMS.png](url)

**Comment by lqd1434** [comment]
you can go to the **_https://editor.rive.app_** and open your rive file then to change its background

**Comment by nzxcvbnm** [comment]
My mistake, I changed it to invisible

**Comment by luigi-rosso** [comment]
Some platforms are case sensitive. Make sure your asset is named the same and is in your pubspec, also try removing any spaces from the name, I've noticed that doesn't always play nice.
