### ISSUE TITLE
Flutter Raster Thread high usage when using complex rive animations

### ISSUE THREAD

**Issue by dario-digregorio** [rive-app/rive-flutter#167]
Hi I already created an issue in the rive feedback. But I think it more belongs here.
https://feedback.rive.app/623

I could see that the more objects you have in your animation the more the flutter raster thread has to process. Is this already known? And are there ways to reduce the work of the raster thread?

![image](https://user-images.githubusercontent.com/32966133/133926989-7ee6e13d-96a3-4947-a0b4-a177f998ac50.png)

**Comment by ignertic** [comment]
are you running the Flutter project in development or production?

**Comment by dario-digregorio** [comment]
I run it in profile Mode otherwise I can't inspect the performance of the application. But even in production I experience the same lag.

**Comment by dario-digregorio** [comment]
Is there any information? I can easily reproduce it. The more objects you add to an artboard, the less performant the rive animation becomes. Is there anything I can do beside reducing the amount of objects I have on my artboard? Thank you

**Comment by caudetgit** [comment]
We've seen performance improvements (e.g., less jankiness) with more recent versions of flutter that included an update [for this issue](https://github.com/flutter/flutter/issues/97334). We suggest that folks update to flutter 3.0.5 or one of the 3.3 pre-releases and see if they also see improved performance.

Closing for now.

**Comment by dario-digregorio** [comment]
Indeed with newer versions Animations are much smoother.
