### ISSUE TITLE
@mustCallSuper error for dispose at lib/src/rive.dart

### ISSUE THREAD

**Issue by cmiscm** [rive-app/rive-flutter#170]
There's @mustCallSuper error for dispose at lib/src/rive.dart

https://github.com/rive-app/rive-flutter/blob/403f7677250cded4d4ebb325bd706b619bb8f9ce/lib/src/rive.dart#L96

97: void dispose() { This method overrides a method annotated as '@mustCallSuper' in 'RenderObject', but doesn't invoke the overridden method.
                     #must_call_super

**Comment by luigi-rosso** [comment]
This is fixed in master!
