### ISSUE TITLE
Get multiple artboards

### ISSUE THREAD

**Issue by Supercaly** [rive-app/rive-flutter#18]
Hi, I'm using this library with a single `.riv` file  that has three artboards inside.

At the moment I'm retrieving the artboards calling 

```dart
riverFile.artboards[0];
riverFile.artboards[1];
riverFile.artboards[2];
```

But sometimes the artboards I'm getting is not the one I wanted.

It's that the correct way of using this or it exists something better, maybe using the artboards name?

**Comment by mjohnsullivan** [comment]
There are a few ways to access the artboards. You can iterate as you're doing now, and you can access the main artboard with the ```file.mainArtboard``` property.

We don't have a method in there yet to get an artboard by name, but that's easily done with something like:

```dart
final artboard = file.artboards.firstWhere(
              (artboard) => artboard.name == 'New Artboard',
              orElse: () => null);
```

I'll look at adding that to ```RiveFile```.

**Comment by Supercaly** [comment]
Ok, I'll try using your method cause it seems more reliable :+1:
