### ISSUE TITLE
[ ^0.7.32 ] 404 error on .riv files when hosted in [ firebase hosting ]

### ISSUE THREAD

**Issue by Shiba-Kar** [rive-app/rive-flutter#181]
![image](https://user-images.githubusercontent.com/24454722/137631886-2d3f52d0-1ba9-4270-9744-6b09f91c6529.png)
**This is the log from chrome from my deployed web app**
while in debug the file loads with no issue !!

![image](https://user-images.githubusercontent.com/24454722/137632076-b3034f55-a6ac-469b-9862-dbabc3a27752.png)

**This is my file structure**

![image](https://user-images.githubusercontent.com/24454722/137632155-7884f301-1260-4a69-8915-105ca25b856a.png)

**This is where it ends up after compilation** 

![image](https://user-images.githubusercontent.com/24454722/137632285-a7bdbf7a-27d4-45ed-bb77-0b53357a09d0.png)

![image](https://user-images.githubusercontent.com/24454722/137632336-cd8e7932-8742-451b-a85e-c8b85eef6c8c.png)

_Originally posted by @Shiba-Kar in https://github.com/rive-app/rive-flutter/issues/60#issuecomment-945136775_

**Comment by HayesGordon** [comment]
Hi @Shiba-Kar, have you managed to resolve this issue? An alternative would be to host the assets and use RiveAnimation.network(url)

If you're still stuck please share the errors in the network inspector on chrome.

**Comment by HayesGordon** [comment]
Closing this as a stale issue, and it's not necessarily related to Rive.
