### ISSUE TITLE
Cannot access certain types in the public library

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rive-app/rive-flutter#182]
### Description

There are a number of types that we can access by using the public API that are not exposed in `lib/rive.dart`.  In order to access them, we need to import from `src/**`, which is discouraged. There is also a lint to prevent doing this:

https://dart-lang.github.io/linter/lints/implementation_imports.html

In the following, I am going to list a number of cases where we need to use implementation imports. I am not sure if the best fix is adding them to `lib/rive.dart`. It might also be beneficial to have a `lib/core.dart` file we could import.

--- 

```
import 'package:rive/src/rive_core/animation/linear_animation.dart';
import 'package:rive/src/rive_core/animation/state_machine_input.dart';
```

Use case: accessing information like the type of animation and name of the animation, passing the animation object around.

---

```
import 'package:rive/src/rive_core/runtime/exceptions/rive_format_error_exception.dart';
import 'package:rive/src/rive_core/runtime/exceptions/rive_unsupported_version_exception.dart';
```

Use case: catching version or format exceptions while dynamically loading Rive files, e.g. from network or the user's local files (in a CMS):

```
try {
  await loadRiveFile();
} on RiveUnsupportedVersionException catch (e) {
  // handle unsupported version.
} on RiveFormatErrorException catch (e) {
  // handle format error.
}
```

---

```
import 'package:rive/src/animation_list.dart';
import 'package:rive/src/rive_core/animation/animation.dart';
```

Use case: querying animations.

---

```
import 'package:rive/src/rive_core/animation/linear_animation.dart';
import 'package:rive/src/rive_core/animation/state_machine_bool.dart';
import 'package:rive/src/rive_core/animation/state_machine_input.dart';
import 'package:rive/src/rive_core/animation/state_machine_number.dart';
```

Use case: querying animations and state machine inputs and working with them, e.g. allowing to select them (by name) in a CMS.

---

```
import 'package:rive/src/rive_core/runtime/runtime_header.dart';
```

Use case: checking the runtime version to check if Rive files are supported.

---

I might have forgotten some, but this should convey the general idea.

### Package structure

@luigi-rosso I think that the current package structure is probably not ideal because idiomatically all implementation files are inside of a `src/` directory and you only have Dart files that `export '';` files from that directly in `lib/`.

**Comment by HayesGordon** [comment]
Closing this due to age and as the API has changed a lot. Feel free to reopen and request additional exports. Please also not that the next major release will make use of the Rive C++ runtime more heavily. So many of these dart export will no longer be relevant.
