### ISSUE TITLE
Super class has no method named 'dispose'

### ISSUE THREAD

**Issue by RRBavda** [rive-app/rive-flutter#184]
I've implemented the following code. 
`
SafeArea(
        child: Center(
          child: RiveAnimation.network(
            'https://cdn.rive.app/animations/vehicles.riv',
          ),
        ),
),
`

I am getting error: "Error: Superclass has no method named 'dispose'.
../…/src/rive.dart:93
        super.dispose();
"

My rive version is   rive: ^0.7.32

Even I've implemented riv file from my assets. But, there is no difference. I am getting same error.

**Comment by Whiskee** [comment]
I get same bug,how to fix it?
