### ISSUE TITLE
How can I migrate from Flare to Rive?

### ISSUE THREAD

**Issue by ovidiudvaro** [rive-app/rive-flutter#186]
Hello,

I have to migrate from Flare to Rive and all that I have is **png** files that were used and generated **flr** files.
Can I do this automatically? Convert from **flr** to **riv** files.
Is there any example on how a migration should go?

Regards!

**Comment by NicolasDionB** [comment]
As I can see, the question remains unanswered! I'm, trying to migrate too but can't find any doc as how to do it.
