### ISSUE TITLE
Key parameter in constructors missing?

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [rive-app/rive-flutter#195]
### Description
I´m experiencing reloading of rive assest in my widget tree, I would like to set a key so that flutter know to reuse the same widget.
However the key parameter seems to be missing from all the constructors. I´m using RiveAnimation.network (but even lower level classes don´t expose the key parameter from the route leaf rendering object).

Could you expose the key parameter in the higher level constructors?

### Steps To Reproduce

Missing api, try to change the widget tree structure that contains a RiveAnimation class and it will reload (show placeholder)

### Expected behavior
Ability to add a key in the constructor to help flutter know to reuse existing widget.

### Device & Versions (please complete the following information)
Any version

**Comment by HayesGordon** [comment]
@LeeMatthewHiggins this is now available on all the RiveAnimation named constructors.

It will also be added to the `Rive` widget soon.

For anyone interested you can also make use of the [KeyedSubtree widget](https://api.flutter.dev/flutter/widgets/KeyedSubtree-class.html)

**Comment by HayesGordon** [comment]
Closing this as this has been exposed for a while now.
