### ISSUE TITLE
Flutter app using Rive won't run in Flutter web debug mode

### ISSUE THREAD

**Issue by alxgibsn** [rive-app/rive-flutter#2]
App won't begin running upon `flutter run -d chrome` if using the runtime. A window is initiated however remains blank and the console never reports service listening.

This only occurs when running without the Skia flag. Running with CanvasKit works fine.

**Comment by creativecreatorormaybenot** [comment]
Works with `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --release`.

**Comment by xpat** [comment]
@alxgibsn @creativecreatorormaybenot I had the same results.  Running $flutter run -d chrome, nothing shows up but a blank window.  I tried it with the Skia flag and it worked.  I didn't try it with CanvasKit.

And on a lark, interestingly enough, I tried it by running $flutter run -d linux.  It opened a window and on the bottom right I saw a blue dot with a white triangle (but no the animation).

**Comment by creativecreatorormaybenot** [comment]
The error in the Javascript console is the following:

<details>
<summary>Uncaught TypeError: Class extends value undefined is not a constructor or null
    at load__packages__rive__src__rive_core__shapes__triangle_dart (component_base.dart:38)
</summary>

```
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

</details>

**Comment by creativecreatorormaybenot** [comment]
Will only run in release mode, even with the flag. See https://github.com/flutter/flutter/issues/64011.

**Comment by mjohnsullivan** [comment]
Fix has gone into Dart for this (https://github.com/flutter/flutter/issues/64011). We'll keep this issue open until the fix has landed in a Flutter channel.

**Comment by mjohnsullivan** [comment]
This appears to be working in latest master and dev builds of Flutter. Example in the runs runs as expected with

```flutter run -d chrome```

**Comment by xpat** [comment]
@mjohnsullivan I just tried it.  It runs correctly on my Chromebook as you indicated with just 

`flutter run -d chrome `

**Comment by creativecreatorormaybenot** [comment]
@mjohnsullivan Yes, that is true 🚀 

I totally forgot about the ticket here as I followed https://github.com/flutter/flutter/issues/64011 so closely 😅
