### ISSUE TITLE
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by MohamedKhalid98** [rive-app/rive-flutter#203]
just update your package and remove the "?" from "WidgetsBinding.instance?.addPostFrameCallback"

because it gives warning after updating flutter

**Comment by anzbert** [comment]
same iossue here. pls submit this minor update

**Comment by anzbert** [comment]
Submitted a PR

**Comment by anzbert** [comment]
Merged. This issue can be closed
