### ISSUE TITLE
Rive animation not importing after I drag and drop local riv file to rive app

### ISSUE THREAD

**Issue by eye-c** [rive-app/rive-flutter#209]
Hi, is it possible to import a finished riv animation from local storage to the Rive app in order to update animation? Whenever I drag and drop my riv file to the Riv app, the assets show but all the animation keyframes are missing.

**Comment by caudetgit** [comment]
You should be able to drag-drop a .riv into the Rive Editor window and have the animation & keyframes included. If this is not working for you, please provide more details.

Closing for now.

**Comment by abarone-btf** [comment]
This is happening, in my case I always get the "upgrade" window, Is it necessary to have a pro plan to import local files? 🤔

**Comment by caudetgit** [comment]
Hi @abarone-btf The Free plan supports .rev imports, but you would need a paid plan to import .riv files.

**Comment by marleykanui** [comment]
Got this from the rive team - getting a pro plan won't make this work either now

"As of Dec 12, 2023, the editor no longer supports importing the .riv file format. We made this change in response to customer concerns about .riv security and to simplify future editor enhancements. Customers on all plans can still export .riv files from the Rive editor for use in their sites and products, which is the purpose of the .riv format. Customers on paid plans can also export/import the .rev format, a complete backup of a Rive project."

**Comment by JoeMandrill** [comment]
> Got this from the rive team - getting a pro plan won't make this work either now
> 
> "As of Dec 12, 2023, the editor no longer supports importing the .riv file format. We made this change in response to customer concerns about .riv security and to simplify future editor enhancements. Customers on all plans can still export .riv files from the Rive editor for use in their sites and products, which is the purpose of the .riv format. Customers on paid plans can also export/import the .rev format, a complete backup of a Rive project."

So how can you import another Rive project from your own work to another project ? Like I want to reuse an animation I've done.
