### ISSUE TITLE
Compiler Optimizations affected by Rive Code when building to Android

### ISSUE THREAD

**Issue by anzbert** [rive-app/rive-flutter#211]
### Description
When compiling a project to APK with Rive as a dependency, certain optimizations are disabled. This is the compiler message:

[   +1 ms] Warning: RiveCoreContext.setObjectProperty from package:rive/src/generated/rive_core_context.dart is too large. Some
optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller
components.
[ +101 ms] Warning: RiveCoreContext.setObjectProperty from package:rive/src/generated/rive_core_context.dart is too large. Some
optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller
components.
[        ] Warning: RiveCoreContext.setObjectProperty from package:rive/src/generated/rive_core_context.dart is too large. Some
optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller
components.

### Steps To Reproduce
1. Add Rive as a dependency to your project in the pubspec.yaml
2. Build for Android with ```flutter build apk```

### Expected behavior
No warning when on building APK.

### Device & Versions (please complete the following information)
- Device: Building on MacOS
- OS: Android SDK 32
- Flutter Version:  latest version 2.10

**Comment by HayesGordon** [comment]
Hi @anzbert, seems like this is resolved. Please feel free to re-open if you're still encountering this issue.
