### ISSUE TITLE
Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding'

### ISSUE THREAD

**Issue by abhayam40** [rive-app/rive-flutter#239]
<-- Thanks for using Rive!

/.rive file:-
https://drive.google.com/file/d/1eG0y-Osu2zkEUHxGfxzY0hFa_lQocSQq/view?usp=sharing

#### Screenshots

/F:/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/rive_render_box.dart:190:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/F:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance?.scheduleFrameCallback(_frameCallback) ?? -1;
                         ^
/F:/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/rive_core/state_machine_controller.dart:220:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/F:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) {
                       ^
/F:/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/controllers/one_shot_controller.dart:40:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/F:/flutter/packages/flutter/lib/src/widgets/binding.dart').
        : WidgetsBinding.instance?.addPostFrameCallback((_) => onStop?.call());

![Screenshot](url)

### Device & Versions (please complete the following information)

Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (4 weeks ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

```

#### Additional context
<-- Add any other context about the problem here. -->

**Comment by renochew** [comment]
Just bump into this problem, hopefully developer would look into it soon.

**Comment by vigshrav** [comment]
**I've been getting similar errors after upgrading Flutter yesterday. Hopefully, someone will look into this.**

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/rive_render_box.dart:190:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
        SchedulerBinding.instance?.scheduleFrameCallback(_frameCallback) ?? -1;
                         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/rive_core/state_machine_controller.dart:220:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.

- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.addPostFrameCallback((_) {
                       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/controllers/one_shot_controller.dart:40:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
        : WidgetsBinding.instance?.addPostFrameCallback((_) => onStop?.call());
                         ^

**Flutter doctor output:**

[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.708], locale en-US)
    • Flutter version 3.0.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\gopal\AppData\Local\Android\sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.1000
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\gopal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.708]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 102.0.1245.33

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by mikeesouth** [comment]
I believe these warnings were fixed by @luigi-rosso in commit https://github.com/rive-app/rive-flutter/commit/7b15ea0cad0b617b68096bbc6f9b0c5456d9aac1
@luigi-rosso are you planning on bumping the version number and push a new version to pub.dev anytime soon? These warnings are quite harmless but still irritating :)

**Comment by zplata** [comment]
Hey all - I recommend upgrading to `0.9.0`, which was just published today, which addresses the suppression of these warnings!
