### ISSUE TITLE
How can i get one of Nested Artboard?

### ISSUE THREAD

**Issue by floki2020** [rive-app/rive-flutter#246]
<-- Thanks for using Rive!

If something isn't working like you expected, please:
- Make sure you've updated rive-flutter to the latest version:
			https://pub.dev/packages/rive/versions
- Check out our help center
			https://help.rive.app/
- You can file a new feature request at
			https://feedback.rive.app/
			
If you think you found a bug or if you can't find what you're looking for 
in our docs, fill out the template below.

-->

### Description
I use the office website demo [rive file](https://rive.app/community/1714-4322-rives-animated-emojis/), and i wanna get one of the Nested Artboard to show! I dont find out some example about Nested Artboards. I'm a newbee in rive. thaks

#### Screenshots

![Screenshot](url)

### Device & Versions (please complete the following information)

```
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (7 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

**Comment by nmarafo** [comment]
Hello @floki2020 ,
Here is the answer: https://github.com/rive-app/rive-flutter/issues/193#issuecomment-1158134343

**Comment by HayesGordon** [comment]
Closing this as complete! Feel free to reopen if needed.
