### ISSUE TITLE
Question: can we pass a String to a animation ?

### ISSUE THREAD

**Issue by Kiruel** [rive-app/rive-flutter#263]
No a bug, justa simple question:

I want to dynamically change a Text inside an animation, can we pass some metadata to the animation ? (I saw custom property with String etc... but can't find any documentation how to use it inside Riveapp.

Thanks !

**Comment by HayesGordon** [comment]
Hi @Kiruel, sorry for not getting back to you sooner. Could you elaborate a bit on what you'd like to be able to do? At the moment it is possible to do some customization/alteration using the Flutter runtime - we're working on demos for this. But in the future, we'd like to make this process easier.

**Comment by HayesGordon** [comment]
I reread your request, and we will have text support soon! 😄
