### ISSUE TITLE
40+% Gpu usage on windows desktop app when playing any riv animation

### ISSUE THREAD

**Issue by obiwanzenobi** [rive-app/rive-flutter#269]
We are using very simple animations in our flutter desktop app. Unfortunately, gpu usage on windows is always around 40% when running rive animation (5% while idle). In comparison - our macos app uses 10% gpu during animation (5% while idle).

We are using rive 0.9.1 flutter package.
Flutter 3.3.8

Tested on various desktop configurations:
(including i5 6600k,16GB, Geforce 2070S), 

Expected behavior: Get at least the same results as on macos.

**Comment by toniarr** [comment]
User sent in the files in HubSpot - links to them are here:
https://app.hubspot.com/file-preview/21376164/file/93356855313/
https://app.hubspot.com/file-preview/21376164/file/93358023055/

Link to ticket: https://app.hubspot.com/contacts/21376164/ticket/1288466307/

**Comment by HayesGordon** [comment]
Hi @obiwanzenobi, just following up. Are you still experiencing this issue?

**Comment by malikhamza88** [comment]
The same problem causes higher CPU usage approx 45% when using onInit and use custom controls, if I don't use the onInit then the usage will reduce to 3%. It also feels noticeable lag on an android device

**Comment by HayesGordon** [comment]
Hi @malikhamza88, can you confirm which version you are using in your `pubspec.lock`. v0.10.0 had a problem with onInit, however this should be solved in v0.10.1

**Comment by malikhamza88** [comment]
I am already using v0.10.1

**Comment by malikhamza88** [comment]
More specifically as soon as I add a controller to the artboard the CPU usage spikes up.

**Comment by HayesGordon** [comment]
Let me investigate. Can you share your .riv file and the code that you use?

Just to confirm, on which platforms are you experiencing this issue?

**Comment by malikhamza88** [comment]
@HayesGordon Here is a demo repo that can reproduce a similar issue
https://github.com/malikhamza88/rive_animation

Note: I have added a TODO comment in **rive_animation_provider.dart** file

**Comment by HayesGordon** [comment]
Hi @malikhamza88 

One of our engineers with both a PC and Mac machine did a quick benchmark and got the following:

```
macOS 12.6 (M1 Pro)      CPU 35%    GPU 12%
Win11 (rtx 3070)         CPU 6%     GPU 18%
```

In the demo that you showed it's not that the onInit is used that is the problem, it's simply that more resources will be used when an animation is active vs. inactive.

There are also differences in Skia for each of these target system that are out of our control as of now.

What I can suggest for your testing is to ensure that you do any performance tests with a release or profile build.

If your rive animation is part of a complex UI, with various other components that do not animate, you can consider wrapping the Rive animation in a [RepaintBoundary](https://api.flutter.dev/flutter/widgets/RepaintBoundary-class.html).

As for Android, I did a test on an old Android device of mine and the animation ran smooth (ensure you test with a profile or release build). But again keep in mind the more complex an animation is, the more resources will be needed to render. There will always be that point where an animation may be too expensive to render for a particular device (especially older hardware).

**Comment by malikhamza88** [comment]
@HayesGordon Sure. Thank you

**Comment by HayesGordon** [comment]
Closing this issue for now, please re-open if you experience issues on a particular platform, or inconsistencies.
