### ISSUE TITLE
Getting windows Error "Connot find LLVM toolset version '15.0.1' when trying to import rive into flutter project on windows

### ISSUE THREAD

**Issue by JerContact** [rive-app/rive-flutter#275]
### Description
Getting an error when trying to build my flutter app when i try and import rive into the pubspec.yaml file.

### Steps To Reproduce
1. I have downloaded the latest visual studio 2022.  
2. I import 'rive: ^0.10.0' into pubspec.yaml file
3. I type "flutter pub add rive" into terminal
4. Everything looks good, then I run the app on windows, and get this error:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Msbuild\Microsoft\VC\v160\Microsoft.Cpp.ClangCl.Common.targets(74,5): error MSB8073: Cannot find LLVM toolset version '15.0.1': the folder ''C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\x64\lib\clang\15.0.1'' does not exist. Please make sure LLVM toolset version '15.0.1' is installed or choose another toolset version. Learn more: https://aka.ms/AA55s5p [C:\Users\Jeremy\Documents\Flutter_TypeAhead\TypeAheadTest\build\windows\plugins\rive_common\rive_common_plugin.vcxproj]
Exception: Build process failed.

### Expected behavior
No errors

#### Additional context
I haven't even tried to use a .riv file yet...just got the dependency in the yaml file is all.  I have even tried to open the "rive_common_plugin.vcxproj" in VS2022 and rebuild with no luck.  I don't know what to do from here

**Comment by ryanaltair** [comment]
from [doc](https://github.com/rive-app/rive-flutter/blob/master/platform_considerations.md)

```
Windows

We use CMake to build rive_plugin.dll. Note that Clang compiler is required, see here for how to enable it in your Visual Studio: https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170
```

**Comment by luigi-rosso** [comment]
@ryanaltair is right, you need to install Clang on Windows.

We've been adding new features which will make use of FFI and require building some native plugins on demand. This only happens the first time you run your app. 

If this isn't convenient for you right now, please use version 0.9.1 for now.

**Comment by luigi-rosso** [comment]
Feel free to re-open the issue if you have more questions.
