### ISSUE TITLE
RiveAnimation.asset('assets/your_animation.riv') -> RiveAnimation.asset('your_animation.riv')

### ISSUE THREAD

**Issue by TiagoMLeite** [rive-app/rive-flutter#276]
### Description
<-- A clear and concise description of what the problem is. -->
First of all, rive is amazing and a great match with flutter. Secondly, I wasn't able to find any open issue talking about what seems to be a simple documentation error. If you use RiveAnimation.network() as described in the documentation, no problem, but when you use RiveAnimation.asset('assets/your_rive_animation.riv') it does not appear on the screen. The fix is very easy, just use it without the 'assets/', RiveAnimation.asset('your_rive_animation.riv').

### Steps To Reproduce
1. Create new project
2. Create assets/ directory
3. Add vehicles.riv to the assets/ directory
4. Put rive dependency in pubsec.yaml
5. Add assets/vehicles dependency in pubsec.yaml
6. In main file import rive package
7. Create a MyHomePage stateless widget with a scaffold, a center, and finally a RiveAnimation.asset('assets/vehicles.riv')

#### Source `.riv`/`.rev` file
download from https://cdn.rive.app/animations/vehicles.riv

### Expected behavior
Should display the rive animation on screen, but doesn't

### Device & Versions (please complete the following information)
- Device: Tested on Chrome browser
- OS: Developed with Windows 10
- Flutter Version:
```
Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git   
Framework • revision cd41fdd495 (7 months ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57                                              
Tools • Dart 2.17.3 • DevTools 2.12.2
```

#### How to Fix
Substitute the path to your .riv file without the 'assets/' ex. 'assets/vehicles.riv' becomes 'vehicles.riv'

**Comment by HayesGordon** [comment]
Hi @TiagoMLeite, sorry for not replying sooner. Could you confirm if this is still an issue? I'm closing this for now as I cannot replicate, and maybe a newer version resolved this. Please reopen if you have any issues
