### ISSUE TITLE
onInit called every setState on parent widget

### ISSUE THREAD

**Issue by ekasetiawans** [rive-app/rive-flutter#277]
<-- Thanks for using Rive!

### Description
<-- A clear and concise description of what the problem is. -->
onInit called every setState on parent widget

### Steps To Reproduce

1. Create a custom widget that returns RiveAnimation.asset
```dart
@override
  Widget build(BuildContext context) {
    return RiveAnimation.asset(
      widget.icon,
      stateMachines: const ['mode'],
      fit: BoxFit.contain,
      onInit: (artboard){
        print('test');
      },
    );
  }
```

2. Put the widget in any StatefulWidget
```dart
class HomePage extends StatefulWidget {
  ...
}

class HomePageState extends State<HomePage> {
...
@override
Widget build(BuildContext context) {
  return Column(
    children: [
      ElevatedButton(
        onPressed: (){
          setState((){});
        },
        child: Text('Set State'),
      ),
      YourRiveAnimationWidget(),
    ]
  );
}
}
```

3. Every we tap the Set State button will print `test` on the debug console. That's mean onInit method is called every setState called on it's parent widget.

### Expected behavior
<-- A clear and concise description of what you expected to happen. -->
onInit method called once

### Device & Versions (please complete the following information)
- Device: [e.g. Android Emulator, iOS Simulator] 
- OS: [e.g. Android SDK API Level 30, iOS 14.5]
- Flutter Version: Copy-paste the output of `flutter --version`
e.g.:
```
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (7 days ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

#### Additional context
<-- Add any other context about the problem here. -->
I have workaround, that the custom widget must be StatefulWidget, and declare onInit method as member of the state class.

```dart
@override
  Widget build(BuildContext context) {
    return RiveAnimation.asset(
      widget.icon,
      stateMachines: const ['mode'],
      fit: BoxFit.contain,
      onInit: _onInit,
    );
  }

void _onInit(artboard) {
  print('this will be printed once');
}
```

**Comment by bdezso** [comment]
There is a serious bug that is causing poor performance in a frequently rebuild context with a rive animation. On an iPhone 13 Pro, the frame rate has dropped from 60 fps to around 20 fps, which is a significant decrease. This is a serious issue that needs to be addressed.

**Comment by luigi-rosso** [comment]
Thanks for reporting, we're looking into it!
