### ISSUE TITLE
0.10.0 SimpleAnimation not work

### ISSUE THREAD

**Issue by xuelongqy** [rive-app/rive-flutter#278]
### Description
After I upgraded from 0.9.1 to 0.10.0, SimpleAnimation doesn't work anymore. I tried reverting to 0.9.1 and it was fine.
I used this rive animation: [lumberjack-squats](https://rive.app/community/980-1894-lumberjack-squats)
The phenomenon is like this: [squats](https://xuelongqy.github.io/flutter_easy_refresh/#/style/squats)
Here is the code used: [squats_indicator](https://github.com/xuelongqy/flutter_easy_refresh/blob/v3/styles/easy_refresh_squats/lib/src/squats_indicator.dart)

### Steps To Reproduce
1. Pull down far enough
2. Release it to trigger the refresh action
3. Seeing the phenomenon, it should be an animation of squatting, but it didn't happen

#### Source `.riv`/`.rev` file
https://rive.app/community/980-1894-lumberjack-squats

### Expected behavior
Perform squat animation

#### Screenshots
https://xuelongqy.github.io/flutter_easy_refresh/#/style/squats

### Device & Versions (please complete the following information)
- Device: [Chrome，Android] 
- Flutter Version: 3.3.10

**Comment by xuelongqy** [comment]
This problem also occurs in other rive animations

**Comment by HayesGordon** [comment]
Hi @xuelongqy! Thanks for creating the issue and providing the detailed information. I tried to reproduce but I was not able to.
- Flutter v3.3.10
- The lumberjack animation

Are you still experiencing this issue? Does it only occur on Chrome/Android?

**Comment by xuelongqy** [comment]
I made some adjustments to RiveAnimation, but I don't know if it will have other effects. (https://github.com/rive-app/rive-flutter/pull/280)
The problem lies in the comparison between controllers and onInit.

**Comment by HayesGordon** [comment]
This is now fixed in v0.10.1 on pub. Thank you again for your contribution @xuelongqy, I had to manually pull in your PR to our upstream repository. Check out the [Changelog](https://pub.dev/packages/rive/changelog) 😉
