### ISSUE TITLE
suggestion: one shot animation should not skip the final frame

### ISSUE THREAD

**Issue by imoldfella** [rive-app/rive-flutter#28]
For one shot animations the last frame should always be delayed if necessary but never skipped. Otherwise stuff gets randomly left visible on the screen that was supposed to be hidden or vice versa.

**Comment by luigi-rosso** [comment]
Oh interesting that's definitely not by design! You're saying that the animation stops rendering too early, basically before applying the final animation frame? Do you have an example/easy repro?

**Comment by imoldfella** [comment]
It only happens randomly. I sort of have on my todo to dig into the code and fix it, but casually inspection suggests the delta time will sometimes skip frames if the cpu falls behind. Normally you wouldn't notice this and its the right thing to do, but for the very last frame it always needs to show it. If you play the animations in this fish https://preview.rive.app/file/fish2/9235 repeatedly, eventually the blink will stay closed or one bubble will stay on the screen.

**Comment by manastyretskyi** [comment]
+ 1 here, I have an animation with opacity and last frames are skipped so the image is half visible

**Comment by luigi-rosso** [comment]
Please try ```rive: ^0.6.8``` which fixes this issue!
