### ISSUE TITLE
could not build application Module "'rive_common'" not found

### ISSUE THREAD

**Issue by anna-bucher** [rive-app/rive-flutter#282]
### Description
could not build application Module "'rive_common'" not found

This happens with the latest version: 0.10.1 downgrading to 0.9.1 fixes the issue at the moment 😊

### Steps To Reproduce
1. Add "rive: ^0.10.1 to pubspec.yaml
2. Try to build of iOS
3. Build fails

### Device & Versions (please complete the following information)
- Device: iOS (iPad)
- OS: 12
- Flutter Version:

```
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (5 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

#### Additional context
Thanks for the great animation toolkit and beautiful work !!!

Muchlove

**Comment by HayesGordon** [comment]
Hi @anna-bucher, thanks for opening. Could you try the following:
```bash
flutter clean
flutter pub get
flutter pub upgrade
cd ios && pod install
```

**Comment by Donquixot228** [comment]
The same problem

**Comment by anna-bucher** [comment]
```
flutter pub upgrade --major-versions

Resolving dependencies...
  [...]
> rive 0.10.1 (was 0.9.1)
+ rive_common 0.0.2
  [...]
Changed 2 dependencies!

Changed 1 constraint in pubspec.yaml:
  rive: ^0.9.1 -> ^0.10.1
```

This solved the issue for me. All good, thanks 💖 !!

PS: I don't have an `ios` folder as the rive wrapper is in a separate library but cleaning and upgrading worked.

**Comment by HayesGordon** [comment]
@Donquixot228 are you still experiencing this issue?

**Comment by Donquixot228** [comment]
> @Donquixot228 are you still experiencing this issue?
No, all fine. Ty

**Comment by HayesGordon** [comment]
Great, thank you. Closing this
