### ISSUE TITLE
`Pointer Exit` listener event is fired only within `Artboard`

### ISSUE THREAD

**Issue by SleepySquash** [rive-app/rive-flutter#284]
### Description
If you attach a listener firing some event on `Pointer Exit` and embed this `Artboard` into a `Flutter` application, then this event is fired only within this `Artboard`. E.g. if your pointer doesn't touch the object this listener is attached to, then it wouldn't fire at all, even if the pointer is indeed outside.

### Steps To Reproduce
1. Embed the provided `.riv` file into an application and add some paddings around it and wrap it with some color (purple, for example).
2. Hover the pointer over the artboard, notice the rectangle becoming red.
3. Move pointer away from any side other than purple one (purple is artboard). Or move the pointer away really fast, so there's no frame with your pointer inside the purple area.
4. Notice rectangle still being red since no `Pointer Exit` was fired.

#### Source `.riv`/`.rev` file
`.rev` and `.riv` files: [hover.zip](https://github.com/rive-app/rive-flutter/files/10508411/hover.zip)

<details>
  <summary>You may use the following code to reproduce this issue (`assets/hover.riv` is the asset)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:rive/rive.dart';

void main() {
  runApp(const MaterialApp(home: RiveApp()));
}

class RiveApp extends StatefulWidget {
  const RiveApp({super.key});

  @override
  State<RiveApp> createState() => _RiveAppState();
}

class _RiveAppState extends State<RiveApp> {
  StateMachineController? _controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: ColoredBox(
            color: Colors.purple,
            child: RiveAnimation.asset(
              'assets/hover.riv',
              onInit: (a) {
                _controller = StateMachineController.fromArtboard(
                  a,
                  a.stateMachines.first.name,
                );
                a.addController(_controller!);

                setState(() {});
              },
            ),
          ),
        ),
      ),
    );
  }
}
```
  
</details>

### Expected behavior
When you move pointer away from the rectangle no matter which side and which speed, you get `Pointer Exit` event and the attached rectangle becomes grey.

#### Screenshots

https://user-images.githubusercontent.com/21217248/214817094-83392e2e-effd-4005-bd8b-f89619ba8964.mp4

### Device & Versions (please complete the following information)
- Device: macOS 
- OS: macOS 13.1
- Flutter Version: 
```
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (6 недель назад) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

**Comment by SleepySquash** [comment]
One may implement a `MouseRegion` wrapping the `Rive` widget, which would manually switch the `Hover` input on and off.

<details>
  <summary>Example widget (input for hover is named `Hover`)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:rive/rive.dart';

class RiveAsset extends StatefulWidget {
  const RiveAsset(this.asset, {super.key});

  final String asset;

  @override
  State<RiveAsset> createState() => _RiveAssetState();
}

class _RiveAssetState extends State<RiveAsset> {
  StateMachineController? _controller;
  SMIBool? _hover;

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (_) => setState(() => _hover?.change(true)),
      onExit: (_) => setState(() => _hover?.change(false)),
      child: RiveAnimation.asset(
        widget.asset,
        fit: BoxFit.contain,
        onInit: (a) {
          _controller = StateMachineController.fromArtboard(
            a,
            a.stateMachines.first.name,
          );
          a.addController(_controller!);

          _hover = _controller?.findInput<bool>('Hover') as SMIBool?;

          setState(() {});
        },
      ),
    );
  }
}
```
  
</details>

With the widget provided above the issue described may be avoided, however this isn't an appropriate solution, as it required `Flutter` code to handle the hovering :(

**Comment by HayesGordon** [comment]
Hi @SleepySquash thanks for opening the issue, and providing fantastic steps to reproduce. I'll take a look into this and get back to you!
