### ISSUE TITLE
APK Build error with v0.10.1

### ISSUE THREAD

**Issue by Kang-Kim1** [rive-app/rive-flutter#286]
I am getting the following exception when building an APK after updating the version to v0.10.1(from 0.9.1) :
```
error: package app.rive.rive does not exist
```
Are there any prerequisites for Android in order to update the version to 0.10.x ?

**Comment by HayesGordon** [comment]
Hi @Kang-Kim1 have you tried a Flutter clean?

Set your version to `^0.10.1` (or whatever the latest is), then:

```bash
flutter clean
flutter pub get
flutter pub upgrade
```

**Comment by Kang-Kim1** [comment]
@HayesGordon Thanks for the comment. I did flutter clean and clear the cache as well, but still getting the same error.

**Comment by HayesGordon** [comment]
Did you do `flutter pub upgrade`

After doing that, can you please confirm which versions are in `pubspec.lock`, you should see `rive` as `0.10.1` and `rive_common` as `0.0.2`

Can you send me the output of `flutter doctor`

Could you also test to see if you can build an APK in a fresh project, with Rive v0.10.1

**Comment by HayesGordon** [comment]
Hi @Kang-Kim1 any update on this issue? Are you still experiencing this?

**Comment by rydwan10** [comment]
Hi, the issue still occurred in version rive: ^0.12.3. Is there any update for this issue? Thanks in advance

**Comment by HayesGordon** [comment]
Closing this issue as there have been many updates to the underlying Android build process, and this should be resolved.

If anyone is still encountering issues, please reopen.
