### ISSUE TITLE
Why not export rive_core/node.dart in rive.dart? 

### ISSUE THREAD

**Issue by ptalmeida** [rive-app/rive-flutter#29]
Same as title, why not

`export 'package:rive/src/rive_core/node.dart';`

in `rive.dart` so we can access nodes and, per example, change the opacity?

**Comment by luigi-rosso** [comment]
Indeed we should! We just haven't gotten to figuring out what the full API access should be. Probably close to everything... we should do this but we want to be cautious so we first exposed little (probably too little).

**Comment by HayesGordon** [comment]
Closing this due to age, and as the API has changed
