### ISSUE TITLE
Rive pub cache size is huge (1gb)

### ISSUE THREAD

**Issue by remonh87** [rive-app/rive-flutter#293]
### Description
When integrating Rive in our CI I noticed a huge spike in build times. It turned out that it exceeded the cache limit of our service provider. I dived a bit more into it and noticed Rive's size in pub cache is huge. Is there a reason why this is so huge and how to optimize the size?

Now Rive alone exceeds the cache limits of CI providers and dramatically slowing down our build times.

![Screenshot 2023-02-23 at 16 12 50](https://user-images.githubusercontent.com/20230599/220968882-bdcbdbe3-1ac8-4bd9-98c6-a33df7e970db.png)

**Comment by mark8044** [comment]
Could it be related to https://github.com/rive-app/rive-flutter/issues/274 ?  Try downgrading to 0.9.1?

**Comment by remonh87** [comment]
@mark8044  thanks I will add my findings to that ticket and close this one.
