### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by NashIlli** [rive-app/rive-flutter#296]
Hey! 

Is there a roadmap with the features that Rive's team is working and on those they will work?

We want to plan migrate to Rive, but we want to know for example if in your roadmap there are features like:
-SFX Integration
-MP4 Integration
-More listeners types
-State machines integration with nested artboards
-Version history in Rive Editor (web) (it helps to prevent lose files when something crash. We lost a file some days ago.)

Thahnks for your help!

**Comment by HayesGordon** [comment]
Hi @NashIlli,

The Flutter runtime is only one of the supported runtimes. For product roadmap questions such as these it'll be better to ask on our Discord channel: https://discord.com/invite/FGjmaTr

There are various channels, including **Feature Requests** where the community can make suggestions and indicate what the highest priority features are.

With regards to version history, that is already possible, see the screenshot:

![CleanShot 2023-03-06 at 11 02 03](https://user-images.githubusercontent.com/13705472/223078983-b63431a3-55e9-4638-922c-32e7ad3694f7.png)

You can also reach out to support if you encounter an issue with accessing your Rive file or a particular revision.

For the runtimes and what they support, please see this [page](https://help.rive.app/runtimes/feature-support)

Closing this for now, but let me know if you have more questions.
