### ISSUE TITLE
Gradle not supported

### ISSUE THREAD

**Issue by arjundevlucid** [rive-app/rive-flutter#299]
Got the issue 
![image](https://user-images.githubusercontent.com/96035930/224927537-7b7e39fa-f15f-408c-a331-e97f867cce69.png)

**Comment by HayesGordon** [comment]
Hi @arjundevlucid

Can you provide some additional information. Which version of Flutter and Rive are you using?

**Comment by HayesGordon** [comment]
Closing this as we've updated the gradle version since this issue was made.
