### ISSUE TITLE
Not animating after attaching controller

### ISSUE THREAD

**Issue by FriendlyNeighbor** [rive-app/rive-flutter#301]
I simply followed your setup to create a controller. didn't do anything regarding the function `_tooglePlay()`. Just straight up added the controller.

```
late RiveAnimationController _controller;

  /// Toggles between play and pause animation states
  void _togglePlay() =>
      setState(() => _controller.isActive = !_controller.isActive);

 @override
  void initState() {
    super.initState();
    _controller = SimpleAnimation('idle');
  }
  
```

and attached _controller to 

```
RiveAnimation.asset(
        'assets/anim.riv',
        controllers: [_controller],
        // Update the play state when the widget's initialized
        onInit: (_) => setState(() {}),
      )
```

but it doesn't animate. it only shows a still image of what the animation looks like when it's completed.

**Comment by HayesGordon** [comment]
Hi @FriendlyNeighbor, do you mind sharing the full code you're using. In the above code snippet it seems like you're not initialising the controller.

Here is an example if you want to create a State Machine Controller: https://github.com/rive-app/rive-flutter/blob/master/example/lib/simple_state_machine.dart

And here is an example to create a Simple Animation Controller: https://github.com/rive-app/rive-flutter/blob/master/example/lib/play_pause_animation.dart

One Shot Controller: https://github.com/rive-app/rive-flutter/blob/master/example/lib/play_one_shot_animation.dart

Custom Controller: https://github.com/rive-app/rive-flutter/blob/master/example/lib/custom_controller.dart

**Comment by HayesGordon** [comment]
Hi @FriendlyNeighbor sorry for the late reply. Can you share the .riv/.rev you're using. One thing that you may do wrong is providing an animation that does not exist. Can you make sure that the animation is named **idle** in the editor.

**Comment by FriendlyNeighbor** [comment]
I did more research into it and finally found that `SimpleAnimation('idle');` "idle" must be the same name as your timeline/animation name in Rive app.

I would suggest to just improve your documentation because even in the `SimpleAnimation ` class, it's also a bit unclear. 

And since some would delete the animation after exporting because the limit for free account is only 3 projects.

**Comment by HayesGordon** [comment]
I'm glad you got it working! For anyone else that stumbles on this there is documentation that gives more detailed steps: https://help.rive.app/runtimes/playback

Closing this issue.
