### ISSUE TITLE
LinearAnimationInstance unable to run one-shot more than once

### ISSUE THREAD

**Issue by BobaTrek** [rive-app/rive-flutter#316]
### Description
The class LinearAnimationInstance sets _didLoop to true after completing a one-shot animation.
The class LinearAnimationInstance then returns false for keepGoing because of the following line of code:
`  bool get keepGoing => animation.loop != Loop.oneShot || !_didLoop;`

Consequently, after running the animation once, setting controller.isActive back to true does not re-run the animation.  Perhaps this is intentional?

### Workaround?
I found the following code will allow you to re-run the animation (scPulse is my SpeedController which uses LinearAnimationInstance:

`scPulse.instance.reset();`
`scPulse.instance.advance(0); // This sets _didloop back to false as a side effect;`
`scPulse.isActive = true;`

Should _didloop be set to false as part of the reset() call (or when isActive gets set false) instead of relying on the side effect of calling advance(0)?

**Comment by HayesGordon** [comment]
Hi @BobaTrek have you taken a look at [OneShotAnimation](https://help.rive.app/runtimes/playback#repeatedly-playing-a-one-shot-animation)?

**Comment by HayesGordon** [comment]
Closing this as it's something we won't change in the short-medium term, and in the long term this underlying Dart code will be replaced with a C++ counterpart and the API will look different.
