### ISSUE TITLE
Update http from 0.13.3 to 1.0.0

### ISSUE THREAD

**Issue by nmarafo** [rive-app/rive-flutter#321]
### Description
In Flutter, if you use Rive with google_fonts, you get http version issues because the latest version of google_font (4.0.5) has been updated to http 1.0.0

### Steps To Reproduce
in pubspec.yaml import google_fonts 4.0.5 and rive 0.11.1

**Comment by HayesGordon** [comment]
Hi @nmarafo thanks for reporting. We'll look into releasing an update with this soon.

In the meantime you could also use decency overrides:
```dart
dependency_overrides:
  http: ^1.0.0
```

**Comment by theemaster** [comment]
`http` package has been updated to `1.1.0`. Is there any update regarding this topic?

**Comment by Imgkl** [comment]
Any updates?

**Comment by HayesGordon** [comment]
Hi @Imgkl, sorry for the delay on this. We're awaiting on some other changes to land before releasing a new version that will have this fix. This should be out soon

**Comment by HayesGordon** [comment]
Version 0.11.5 now uses the newest release of HTTP
