### ISSUE TITLE
Execution failed for task ':rive_common:compileDebugKotlin'.

### ISSUE THREAD

**Issue by Hami0095** [rive-app/rive-flutter#322]
I am using the lates rive_package with http package as dependency_overrides
I have just recently upgraded to Flutter:

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> [√] Android toolchain - develop for Android devices (Android SDK version 33.0.2) 
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.26)
> [√] Android Studio (version 2022.1)
> [√] VS Code (version 1.78.2)
> [√] Connected device (4 available)
> [√] Network resources

During execution the execution was terminated due to following error:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rive_common:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details`

**Comment by HayesGordon** [comment]
Hi @Hami0095, which version of the runtime were you on before updating?

Please see the platform considerations: https://github.com/rive-app/rive-flutter/blob/master/platform_considerations.md

It may be that you need to set the NDK version higher, or update Clang

**Comment by HayesGordon** [comment]
Closing this as there has not been any answer in a while. The runtime has also undergone plenty of changes and fixes since this report.
