### ISSUE TITLE
Erro build flutter web with rive 0.11.5

### ISSUE THREAD

**Issue by JgomesAT** [rive-app/rive-flutter#333]
With the las version of rive 0.11.5 I cant compile flutter web I have this error:

Target dart2js failed: Exception: lib/presentation/ui/widgets/features/authentication/authentication_form.dart:40:11:
Error: A value of type 'Type/*1*/' can't be assigned to a variable of type 'Type/*2*/'.
 - 'Type/*1*/' is from 'dart:core'.
 - 'Type/*2*/' is from 'package:rive/src/asset.dart' ('/home/tfsapp/.pub-cache/hosted/pub.dev/rive-0.11.5/lib/src/asset.dart').
          ToggleFluskyIntent: CallbackAction<ToggleFluskyIntent>(onInvoke: (ToggleFluskyIntent intent) => viewModel.toggleEasterEgg()),
          ^
lib/presentation/ui/widgets/features/authentication/authentication_form.dart:39:40:
Error: The argument type 'Map<Type/*1*/, Action<Intent>>' can't be assigned to the parameter type 'Map<Type/*2*/, Action<Intent>>'.
 - 'Map' is from 'dart:core'.
 - 'Type/*1*/' is from 'package:rive/src/asset.dart' ('/home/tfsapp/.pub-cache/hosted/pub.dev/rive-0.11.5/lib/src/asset.dart').
 - 'Action' is from 'package:flutter/src/widgets/actions.dart' ('../../../_tool/Flutter/3.10.6/linux/flutter/packages/flutter/lib/src/widgets/actions.dart').
 - 'Intent' is from 'package:flutter/src/widgets/actions.dart' ('../../../_tool/Flutter/3.10.6/linux/flutter/packages/flutter/lib/src/widgets/actions.dart').
 - 'Type/*2*/' is from 'dart:core'.
        actions: <Type, Action<Intent>>{
                                       ^

**Comment by HayesGordon** [comment]
Hi @JgomesAT, can you replicate the compilation failure in a new Flutter project?

What platform are you on?

Have you tried cleaning your project
```bash
flutter clean
flutter pub get
flutter pub upgrade
```

**Comment by JgomesAT** [comment]
HI,

the problem is that:

The argument type 'Map<Type, Action<Intent>> (where Type is defined in /Users/.pub-cache/hosted/pub.dev/rive-0.11.5/lib/src/asset.dart)' can't be assigned to the parameter type 'Map<Type, Action<Intent>> (where Type is defined in /Users//Development/Flutter2_SDK/flutter/bin/cache/pkg/sky_engine/lib/core/type.dart)'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)
map.dart(30, 16):

the type is not the same in this code:
Actions(
        actions: **Map<Type, Action<Intent>>**{
          ToggleFluskyIntent: CallbackAction<ToggleFluskyIntent>(onInvoke: (ToggleFluskyIntent intent) => viewModel.toggleEasterEgg()),
        },
        
by now I have removed the type annotation and the code compiles well, but in previous versions, this annotation worked well

**Comment by HayesGordon** [comment]
There were some deprecations in 0.11.5, but there should not have been anything breaking in the public API.

Glad you sorted it. Going to close this for now, but feel free to reopen.
