### ISSUE TITLE
Follow path not working

### ISSUE THREAD

**Issue by user97116** [rive-app/rive-flutter#339]

**Comment by HayesGordon** [comment]
Hi @user97116 can you provide more information please. A reproducible example will be great.

Also note that you need to be on a later version of Rive: https://help.rive.app/runtimes/feature-support

For follow path you need to be using at least: v0.11.6

**Comment by user97116** [comment]
@HayesGordon check this https://rive.app/s/D8Fw3SKX6kmVCge_f6OlyQ/ simple path animation but you use this riv file in flutter it won't work, I am using latest rive

**Comment by HayesGordon** [comment]
I just tested and it works fine for me. Can you share the code you're using.

**Comment by HayesGordon** [comment]
Hi @user97116, any update on this? If you can provide a sample that demonstrates the issue that'll be helpful.

**Comment by bjartebore** [comment]
Not sure if this is exactly the same issue, but I am experiencing issues with follow path together with state machine and blend state (1D). Running my state machine through the rive application works as expected my sun and moon moves smoothly white updating my input value (from 0 -24), but when I run the animation in the flutter app. The animation runs weirdly going back end forward on the path.

I have posted a simplified version of my animation to the community https://rive.app/community/8645-16533-day-night-cycle/ 

I have also created a sample flutter application where you can test the animation with a slider.
https://github.com/bjartebore/rive_path_issue 

@HayesGordon

**Comment by HayesGordon** [comment]
Closing this as resolved as part of the linked issue. A future API change will make this less likely to run into
