### ISSUE TITLE
Text feature error in Flutter App - "RangeError"

### ISSUE THREAD

**Issue by NashIlli** [rive-app/rive-flutter#344]
### Description
There is an error when trying to use a Rive file with a Text (new feature of River). The text it is not rendered and shows an error in the console related to "paragraph index".
### Steps To Reproduce
1. Create an empty new Flutter project
2. Install latest version of rive (0.11.16)
3. Add RiveAnimation.asset('...') widget to the renderized main widget. Use the file attached. It's a super simple text in a Rive artboard.
4. The following error appear: 
```
======== Exception caught by rendering library =====================================================
The following RangeError was thrown during paint():
RangeError (index): Invalid value: Only valid value is 0: 1
```
#### Source `.riv`/`.rev` file

[text-rive-test.zip](https://github.com/rive-app/rive-flutter/files/12540707/text-rive-test.zip)

### Expected behavior
The RiveAnimation with text should be renderized in the Flutter App.
#### Screenshots
![image](https://github.com/rive-app/rive-flutter/assets/6954280/25554deb-5659-4513-b879-9d7b80df50bf)

### Device & Versions (please complete the following information)
- Device:  Android Emulator
- OS: Android SDK API Level 33
- Flutter Version:
```
Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ff5b5b5fa6 (13 days ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0
```

**Comment by NashIlli** [comment]
It was using Gradle 7.5 
After updating to Gradle 8 it worked properly

**Comment by NashIlli** [comment]
It was using Gradle 7.5
After updating to Gradle 8 it worked properly

**Comment by sheetalsavani** [comment]
I'm using rive: ^0.12.4 and gradle 8 still having the same error
