### ISSUE TITLE
Rive should have a mobile app to showcase our prototype

### ISSUE THREAD

**Issue by ljoly83** [rive-app/rive-flutter#349]
Figma have an iOS and Android application that allow to show our prototype to customer.
For rive this would be  a (MUST HAVE) very nice feature!
https://help.figma.com/hc/en-us/articles/1500007537281-Guide-to-the-Figma-mobile-app

**Comment by HayesGordon** [comment]
Hi @ljoly83 , great suggestion!

This would be a general product feature, and not rive-flutter related (though maybe if the app is built with Flutter).

You should definitely make this suggestion on Rive's Discord in the feature-request channel: https://discord.com/invite/FGjmaTr

Going to close this issue as it doesn't make sense for this request to live here.
