### ISSUE TITLE
How to clone a character (Instancing)?

### ISSUE THREAD

**Issue by special-k** [rive-app/rive-flutter#35]
Is it possible to programmatically clone a character along with the whole animation?

**Comment by mjohnsullivan** [comment]
Can you expand on what you mean by character, and what you're trying to achieve?

If you want to create multiple instances of animations, we don't have instancing yet, but it's something we're actively looking into and supporting in all our runtimes.

**Comment by special-k** [comment]
I want to copy the geometry along with the animation.
![image1227](https://user-images.githubusercontent.com/184527/102678329-6d205700-41c9-11eb-9f87-4abfa7810454.png)
In the code, it would be something like this
[code]Animation heroWalk2 = artboard.animations.getByName('hero_walk').cloneTo(newName, newGeom);[/code]

**Comment by luigi-rosso** [comment]
We've added support for instancing artboards, this requires breaking your project into separate artboards and then assembling them in your runtime (Flutter now supports instancing). 

For example, you could have one hero character with all the movement/attack animations in one artboard. You can instance the hero artboard multiple times and apply those animations at different times to each instance of the hero. The api introduced for this is just "artboard.instance()" which returns a cloned version of the artboard.
