### ISSUE TITLE
display an SVG image network

### ISSUE THREAD

**Issue by babakoto** [rive-app/rive-flutter#350]
Hello , 
Is it possible to display an SVG image (Network) in Rive? For example, I want to display a user's profile image in the Rive animation.

**Comment by HayesGordon** [comment]
Hi @babakoto it's possible to swap out raster images (not SVGs), but the current API for this is still experimental, but should release this week or very soon after. Keep an eye on Discord + releases for more info

**Comment by babakoto** [comment]
thank you for the answer
