### ISSUE TITLE
Hitting a random build error when building the Flutter module package for Android (.aar) with the Rive plugin

### ISSUE THREAD

**Issue by weifengsonos** [rive-app/rive-flutter#352]
### Description
Hitting a random build error when building the Flutter module package for Android (.aar) with the Rive plugin

### Steps To Reproduce
The latest "rive_common-0.2.7" plugin seems to have the dependency on NDK version "25.1.8937393".  But one of the most current Flutter SDK version "3.13.6" still has the dependency on NDK version "23.1.7779620".  As the result, we are hitting the random build error below when building the Flutter module package for Android (the .aar file) together with the Rive plugin.  To fix this issue, we have to manually bump up the NDK version for the Flutter SDK.  But to do this, it will require us to do some extra work in our build scripts as the same Flutter SDK is being used by several Flutter projects.  Simply bumping up the NDK version requirement in the Flutter SDK might break others.  So we were wondering if the Rive team can consider just using the same NDK version as the current Flutter SDK is using:-).

* What went wrong:
Flutter failed to build:
> One or more plugins require a higher Android NDK version.
 Fix this issue by adding the following to /<path_to_Flutter_module>/.android/Flutter/build.gradle:
 android {
  ndkVersion "25.1.8937393"
  ...
 }

**Comment by HayesGordon** [comment]
Hi @weifengsonos, unfortunately this won't be possible. The Rive runtime makes use of modern features that are only available in newer NDK versions, `25.1.8937393` and up.

**Comment by weifengsonos** [comment]
Hi @HayesGordon, thanks for your quick response!  No problem... At least we tried:-).
