### ISSUE TITLE
Migrate to `package:web` to support WASM

### ISSUE THREAD

**Issue by IchordeDionysos** [rive-app/rive-flutter#375]
### Description

The short version:
- Migrate usage of dart:html to package:web
- Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop

This will allow compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

#### Additional context

**Conditional imports:**
https://github.com/search?q=repo%3Arive-app%2Frive-flutter%20dart.library.html&type=code
They need to be changed to `dart.library.js_interop`

Potentially also some changes would have to be done in `rive_common` to make sure no `ffi` gets not imported on web ☺️

**Comment by IchordeDionysos** [comment]
# Changes required

A couple (not all) of required changes ☺️ (as I've seen those being missed in other PRs).
Especially the conditional imports is something that is not obvious.

## rive_common

### `platform.dart`

```diff
import 'src/platform_native.dart'
-    if (dart.library.html) 'src/platform_web.dart';
+    if (dart.library.js_interop) 'src/platform_web.dart';
```

### `rive_text.dart`

```diff
import 'src/rive_text_ffi.dart'
-    if (dart.library.html) 'src/rive_text_wasm.dart';
+    if (dart.library.js_interop) 'src/rive_text_wasm.dart';
```

### `src/rive_text_wasm.dart`

```diff
-import 'dart:html' as html;
-import 'dart:js' as js;
+import 'package:web' as html;
+import 'dart:js_interop' as js;
```

```diff
-var script = html.ScriptElement()
+var script = html.HTMLScriptElement()
```

## rive

### `lib/src/platform.dart`

```diff
-import 'platform_native.dart' if (dart.library.html) 'platform_web.dart';
+import 'platform_native.dart' if (dart.library.js_interop) 'platform_web.dart';
```

### `lib/src/rive_file.dart`

```diff
import 'package:rive/src/local_file_io.dart'
-    if (dart.library.html) 'package:rive/src/local_file_web.dart';
+    if (dart.library.js_interop) 'package:rive/src/local_file_web.dart';
```

**Comment by HayesGordon** [comment]
Hey all, the Rive Flutter package **v0.13.5** addresses this and now uses `dart:js_interop` and `package:web` APIs.

Please reopen if you encounter any difficulties.
