### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by mjohnsullivan** [rive-app/rive-flutter#38]
This is planned once null safety is out of beta.

**Comment by IchordeDionysos** [comment]
@mjohnsullivan the Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

There are no more breaking changes planned :)

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by franarolas** [comment]
Any news on that?

**Comment by SergioEric** [comment]
Can we collaborate with the migration ?

**Comment by yanshouwang** [comment]
looking forward~

**Comment by mjohnsullivan** [comment]
We're kicking off migrating the package to null safety next week. We'll keep everyone updated on progress here as we work through it.

**Comment by enyo** [comment]
@mjohnsullivan any branch we can use until it's published

**Comment by mjohnsullivan** [comment]
We're in the middle of converting our entire Dart codebase to NNBD, as parts are shared between our runtime and our editor. There's a lot of code to convert, and it's taking time.

We're not quite there yet, but we'll have a branch available as soon as we have a work runtime.

**Comment by Will-Swain-Sprout** [comment]
Hey guys, just checking in with how're you progressing with the null safety and the runtimes? Thanks so much for all the hard work!

**Comment by mjohnsullivan** [comment]
We're all migrated; 0.7.2 is up on pub: https://pub.dev/packages/rive
