### ISSUE TITLE
Erro with rive_common-0.4.7 on Android

### ISSUE THREAD

**Issue by JgomesAT** [rive-app/rive-flutter#385]
When try to run my app in Android I HAve this error with the rive version rive 0.13.3

* What went wrong:
Execution failed for task ':rive_common:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/android/.cxx/Debug/3l671ga5/arm64-v8a'
CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/renderer.cpp.o
  [2/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/math/mat2d.cpp.o
  [3/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/audio/audio_sound.cpp.o
  [4/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/text/line_breaker.cpp.o
  [5/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/audio/audio_source.cpp.o
  [6/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/audio/audio_reader.cpp.o
  [7/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive_text/rive_text.cpp.o
  [8/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/math/raw_path.cpp.o
  [9/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-buffer-verify.cc.o
  [10/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-blob.cc.o
  [11/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-buffer-serialize.cc.o
  [12/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-common.cc.o
  [13/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-draw.cc.o
  [14/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/text/font_hb.cpp.o
  ......
  
  
   FAILED: /Users/git/at-app/app_andorratelecom/build/rive_common/intermediates/cxx/Debug/3l671ga5/obj/arm64-v8a/librive_text.so 
   
   ....
   
   
     ld: error: undefined hidden symbol: OT::cff2::accelerator_t::get_extents(hb_font_t*, unsigned int, hb_glyph_extents_t*) const
  >>> referenced by hb-subset-plan.cc:1019 (/Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-subset-plan.cc:1019)
  >>>               CMakeFiles/rive_text.dir/Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-subset-plan.cc.o:(_update_instance_metrics_map_from_cff2(hb_subset_plan_t*))
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      /Users/Library/Android/sdk/cmake/3.18.1/bin/ninja \
        -C \
        /Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/android/.cxx/Debug/3l671ga5/arm64-v8a \
        rive_text
    from /Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/android

if I us a depe3ndenci overide and unse the previous version rive_common-0.4.5 works fine

**Comment by berhili098** [comment]
> When try to run my app in Android I HAve this error with the rive version rive 0.13.3
> 
>     * What went wrong:
>       Execution failed for task ':rive_common:buildCMakeDebug[arm64-v8a]'.
> 
> 
> > com.android.ide.common.process.ProcessException: ninja: Entering directory `/Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/android/.cxx/Debug/3l671ga5/arm64-v8a'
> > CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/renderer.cpp.o
> > [2/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/math/mat2d.cpp.o
> > [3/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/audio/audio_sound.cpp.o
> > [4/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/text/line_breaker.cpp.o
> > [5/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/audio/audio_source.cpp.o
> > [6/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/audio/audio_reader.cpp.o
> > [7/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive_text/rive_text.cpp.o
> > [8/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/math/raw_path.cpp.o
> > [9/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-buffer-verify.cc.o
> > [10/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-blob.cc.o
> > [11/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-buffer-serialize.cc.o
> > [12/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-common.cc.o
> > [13/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-draw.cc.o
> > [14/84] Building CXX object CMakeFiles/rive_text.dir/Users/jorgegomes/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/rive-cpp/src/text/font_hb.cpp.o
> > ......
> 
> FAILED: /Users/git/at-app/app_andorratelecom/build/rive_common/intermediates/cxx/Debug/3l671ga5/obj/arm64-v8a/librive_text.so
> 
> ....
> 
> ```
>  ld: error: undefined hidden symbol: OT::cff2::accelerator_t::get_extents(hb_font_t*, unsigned int, hb_glyph_extents_t*) const
> ```
> 
> > > > referenced by hb-subset-plan.cc:1019 (/Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-subset-plan.cc:1019)
> > > > CMakeFiles/rive_text.dir/Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/ios/harfbuzz/src/hb-subset-plan.cc.o:(_update_instance_metrics_map_from_cff2(hb_subset_plan_t*))
> > > > clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> > > > ninja: build stopped: subcommand failed.
> 
> C++ build system [build] failed while executing: /Users/Library/Android/sdk/cmake/3.18.1/bin/ninja -C /Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/android/.cxx/Debug/3l671ga5/arm64-v8a rive_text from /Users/.pub-cache/hosted/pub.dev/rive_common-0.4.7/android
> 
> if I us a depe3ndenci overide and unse the previous version rive_common-0.4.5 works fine

have tried upgrading gradle

**Comment by JgomesAT** [comment]
what version of gradel, currently I have this 

distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip

 id "com.android.application" version "7.3.0" apply false

**Comment by FernandoUFS** [comment]
I'm having the same issue after upgrade to rive 0.13.3, using dependency override as @berhili098 said, helped me for now.

My flutter version is stable 3.19.5. 
gradle:7.2.0
gradle-7.5-all.zip

**Comment by monstar-harsh** [comment]
having same after updating rive 0.13.3

**Comment by philter** [comment]
Hi all, please upgrade to 0.13.4 as the issues you are seeing should be resolved.

**Comment by jeevansonm** [comment]
Was facing the same issue with 0.13.3 & 0.13.1 versions. Upgraded to 0.13.4 and the issue has been resolved. Thanks @philter
