### ISSUE TITLE
Rive not being able to lookup init symbol on iOS

### ISSUE THREAD

**Issue by jaggernod** [rive-app/rive-flutter#392]
### Description
Rive animation is not being shown due to the inability to load `init` symbol on iOS devices (Android and Linux work fine)

### Steps To Reproduce

1.  Load any Rive file on iOS

### Expected behavior
A rive animation is shown and running

#### Screenshots
No need, there is just an empty space in place of the Rive widget

### Device & Versions (please complete the following information)
- iOS Simulator, iPhone SE
- OS: 17.5 ,15.8.2 
- Flutter Version: 
```
Flutter 3.19.5 • channel [user-branch] • unknown source
Framework • revision 300451adae (8 weeks ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1
```
- Rive version: 0.13.4

#### Additional context
Logs from the application:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'init': dlsym(RTLD_DEFAULT, init): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      init (package:rive_common/src/rive_text_ffi.dart:527:15)
#2      init (package:rive_common/src/rive_text_ffi.dart)
#3      initFont (package:rive_common/src/rive_text_ffi.dart:836:3)
#4      Font.initialize (package:rive_common/rive_text.dart:477:7)
#5      RiveFile.initializeText (package:rive/src/rive_file.dart:365:33)
#6      RiveFile._initTextAndImport (package:rive/src/rive_file.dart:381:13)
#7      RiveFile.asset (package:rive/src/rive_file.dart:411:12)
<asynchronous suspension>
#8      RiveAnimationState._configure (package:rive/src/widgets/rive_animation.dart:212:11)
<asynchronous suspension>
```

**Comment by jaggernod** [comment]
Apologies, after further investigation it turned up that it was not the fault of Rive Library. 
We had another library messing up the library linking.

Closing this issue.

**Comment by KestasVenslauskas** [comment]
Having the same issue, what was the fix for you?

**Comment by samariotorres** [comment]
im encountering something similar with a Rive asset on the latest version of flutter 

```
flutter: Invalid argument(s): Failed to lookup symbol 'init': dlsym(RTLD_DEFAULT, init): symbol not found
flutter: 
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
ffi_dynamic_library_patch.dart:33
#1      init (package:rive_common/src/rive_text_ffi.dart:493:16)
rive_text_ffi.dart:493
#2      init (package:rive_common/src/rive_text_ffi.dart)
#3      initFont (package:rive_common/src/rive_text_ffi.dart:810:3)
rive_text_ffi.dart:810
#4      Font.initialize (package:rive_common/rive_text.dart:461:7)
rive_text.dart:461
#5      RiveFile.initialize (package:rive/src/rive_file.dart:392:33)
rive_file.dart:392
#6      RiveFile._initTextAndImport (package:rive/src/rive_file.dart:414:13)
rive_file.dart:414
#7      RiveFile.asset (package:rive/src/rive_file.dart:444:12)
rive_file.dart:444
<asynchronous suspension>
#8      RiveAnimationState._configure (package:rive/src/widgets/rive_animation.dart:212:11)
rive_animation.dart:212
<asynchronous suspension>
flutter: ---------------------------------------
```

**Comment by romme86** [comment]
Same here, error popping up in the latest flutter version

`flutter: 
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      init (package:rive_common/src/rive_text_ffi.dart:493:16)
#2      init (package:rive_common/src/rive_text_ffi.dart)
#3      initFont (package:rive_common/src/rive_text_ffi.dart:810:3)
#4      Font.initialize (package:rive_common/rive_text.dart:461:7)
#5      RiveFile.initialize (package:rive/src/rive_file.dart:392:33)
#6      RiveFile._initTextAndImport (package:rive/src/rive_file.dart:414:13)
#7      RiveFile.asset (package:rive/src/rive_file.dart:444:12)
<asynchronous suspension>
#8      RiveAnimationState._configure (package:rive/src/widgets/rive_animation.dart:212:11)
<asynchronous suspension>
flutter: ----------------------------------------------------
flutter: An error occurred in DEV: Invalid argument(s): Failed to lookup symbol 'init': dlsym(RTLD_DEFAULT, init): symbol not found`

**Comment by asa-012** [comment]
In my case, I solved it by using dynamic linking in my Podfile:

`use_frameworks!`

Rive uses Dart FFI to dynamically load native symbols (like "init"), but with static linking these symbols aren’t exported, causing dlsym to fail.
Switching to dynamic linking ensures the symbols are correctly available, resolving the error.
