### ISSUE TITLE
Performance problem when I load a Rive Animation in my flutter app

### ISSUE THREAD

**Issue by Ismaelito86** [rive-app/rive-flutter#396]
I have a performance problem when I load a Rive Animation in my flutter app. I'm using last version of rive flutter package (0.13.7) and last version of flutter framework, I’m also using an iphone 15 pro device and when I load the animation, the cpu works at 80% and makes the device heat up, I'm already using skia as a rendering engine. This happens even without having any simple svg shape in the artboard (in the rive side), just having a timeline animation even empty  is enough for get this behavior on the device. How can I fix this? Thanks a lot

**Comment by HayesGordon** [comment]
Hi @Ismaelito86,

Some things you can try on your side:
- Test on both Impeller and Skia to rule out if it’s a rendering bug
- Test other Rive files to see if it isn’t isolated to the file you’re testing
- Ensure you’re testing with a profile/release build

If you’re adding the animation to your app that has other logic/UI on screen, you might be causing Flutter to redraw all of that UI for each frame that Rive updates. You can wrap the Rive widget in a [RepaintBoundary](https://api.flutter.dev/flutter/widgets/RepaintBoundary-class.html) to ensure Rive doesn’t cause those other widgets to repaint.

It could be that there’s an issue with this animation file, and it’s in some strange condition that is causing the high usage—or, potentially, a bug with Skia in drawing those shapes/paths.

If you still have issues, please share an example project with us. A fresh project that has the animation, along with the code you’re using, so we can investigate the issue further.

**Comment by HayesGordon** [comment]
Closing this issue as no additional information has been provided to reproduce the above results. We're also working on bringing the Rive Renderer to the Rive Flutter runtime, which should greatly enhance performance; see https://github.com/rive-app/rive-flutter/issues/388
