### ISSUE TITLE
Rive incompatible with newer NDK version?

### ISSUE THREAD

**Issue by WingToh** [rive-app/rive-flutter#398]
It seems that Rive requires NDK version "25.1.8937393". I have a newer NDK version but Rive does not work with the newer version?
![image](https://github.com/rive-app/rive-flutter/assets/60434526/153f2ff6-0b6c-4b07-850e-890e8ecdde92)
I dont encounter this problem when I remove Rive from my project.

I use the latest version NDK with "flutter.ndkVersion" in my build.gradle file: 
![image](https://github.com/rive-app/rive-flutter/assets/60434526/aede7768-2d79-4420-be7c-3a0ec1085685)
That is, version 27.0.11718014 
![image](https://github.com/rive-app/rive-flutter/assets/60434526/ffbdc445-ddd5-45f0-a2ec-39c396880e11)

Am I missing something? Why is Rive still on an older version?

**Comment by bennibau** [comment]
+1 We have NDK 26.2.11394342 and cannot build Android anymore

**Comment by JgomesAT** [comment]
I have the same problem

A problem occurred configuring project ':rive_common'.
> [CXX1104] NDK from ndk.dir at /Users//Library/Android/sdk/ndk/27.0.11902837 had version [27.0.11902837] which disagrees with android.ndkVersion [25.1.8937393]

**Comment by bbo76** [comment]
+1

**Comment by abdullah10182** [comment]
+1
