### ISSUE TITLE
Please update web dependency

### ISSUE THREAD

**Issue by mark8044** [rive-app/rive-flutter#413]
It looks like alot of packages have moved onto `web` 1.0.0 https://pub.dev/packages/web, which is creating conflicts with rive.  For example: `So, because ... depends on both cached_network_image ^3.4.1 and rive ^0.13.12, version solving failed.`

**Comment by HayesGordon** [comment]
Hi @mark8044, we can look into updating this dependency. Could you try for now with a [dependency_override](https://stackoverflow.com/questions/23031384/how-to-specify-dependency-overrides-in-pubspec-yaml)?

**Comment by mark8044** [comment]
@HayesGordon Sure its not a problem for me, I can get around the issue easily.  But I see the problem growing, since all the official XXX_plus packages (https://pub.dev/packages/share_plus, https://pub.dev/packages/connectivity_plus, https://pub.dev/packages/package_info_plus, etc...). have also moved to Web 1.0.0

Thanks for looking into this

**Comment by mark8044** [comment]
@HayesGordon 
The issue is becoming more widespread as I see more and more packages move to Web 1.0.0.  The list is >10 now on my repo

**Comment by HayesGordon** [comment]
@mark8044 thanks for following up. The next release will have this in. Should be tomorrow

**Comment by OlegNovosad** [comment]
> @mark8044 thanks for following up. The next release will have this in. Should be tomorrow

Never specify hard dates :D

**Comment by HayesGordon** [comment]
Hah @OlegNovosad. Luckily I said _should be_ and not _will be_

This should now be resolved in v0.13.13

We've increased the dependency range.

Please reopen if you're still experiencing issues after upgrading.
