### ISSUE TITLE
        ndkVersion = "25.1.8937393"

### ISSUE THREAD

**Issue by Pawankant87** [rive-app/rive-flutter#418]
Your project is configured with Android NDK 23.1.7779620, but the following plugin(s) depend on a different Android NDK version:
- rive_common requires Android NDK 25.1.8937393
Fix this issue by using the highest Android NDK version (they are backward compatible).
Add the following to C:\Users\mindp\StudioProjects\dfms\android\app\build.gradle:

    android {
        ndkVersion = "25.1.8937393"
        ...
    }

**Comment by Tudolla** [comment]
i do the same problem . Did you fix this?

**Comment by HayesGordon** [comment]
Rive requires later NDK versions to compile the native code Rive uses. You can compile with a previous version but it will result in a large APK size. Setting a higher NDK is backwards compatible, as the error message above says.

But if you want you can also override the Android NDK version Rive requires by setting `rive.ndk.version` in `gradle.properties`. For example: `rive.ndk.version=26.3.11579264`. This will get rid of the warning, but we recommend using at least "25.1.8937393." - See https://github.com/rive-app/rive-flutter/issues/398.

**Comment by abdullah10182** [comment]
The proposed solution does not work on a default flutter app.
