### ISSUE TITLE
Auto Scale Text Issue

### ISSUE THREAD

**Issue by tguerin** [rive-app/rive-flutter#422]
### Description
We're trying to use the auto scale feature in our project. It works perfectly in the editor, but once we integrate it into our Flutter app, the text breaks into multiple lines. We are using the 0.13.13 version.

### Steps To Reproduce
1. Define rive with fit text
![Screenshot 2024-09-23 at 22 33 18](https://github.com/user-attachments/assets/74642697-6e19-476b-a3ff-d008fd3277d5)

2. Load rive in flutter

3. Trigger text update with long text

4. Text breaks on multiline

#### Source `.riv`/`.rev` file

[text_fit_scale.riv.zip](https://github.com/user-attachments/files/17110277/text_fit_scale.riv.zip)

### Expected behavior
The text should size down

#### Screenshots
 
https://github.com/user-attachments/assets/16b4c359-4399-4749-8cbf-97a5a2744957

### Device & Versions (please complete the following information)
Mainly tested on simulator
```
Flutter 3.24.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5874a72aa4 (5 weeks ago) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2
```

#### Additional context

Tested on Impeller and Skia.

**Comment by HayesGordon** [comment]
Thanks for reporting the issue, this should now be resolved in v0.13.15
