### ISSUE TITLE
Is it possible to export/manipulate the current frame of a paused animation?

### ISSUE THREAD

**Issue by htmnk** [rive-app/rive-flutter#45]
On the [Rive's landing page](https://beta.rive.app/), it is stated that:

> Or switch it up!
> Of course, all of this can be manipulated with code to add even more interactivity. Connect your graphics to data, swap out images at runtime, change colors, follow the mouse position, and more.

are there currently any docs about this?

I have an idling character, ideally I would like to pause the animation with one button and take a screenshot of the current state of my artboard programmatically with another button. The closest thing I could find for achieving this in Flutter is to use a [RenderRepaintBoundry.toImage()](https://stackoverflow.com/questions/41957086/creating-raw-image-from-widget-or-canvas). I was wondering if there is any "Rive" way to achieve this?

**Comment by luigi-rosso** [comment]
In regards to switching things up, you can use a controller to query the hierarchy and change objects (like an animation would, but you do it with code). We need to provide more documentation/examples of this!

For part 2, you could do this by putting the Rive widget in a RepaintBoundary and then calling toImage, we don't have another way to do this in Flutter.

**Comment by luigi-rosso** [comment]
Closing this for now, but please re-open or feel free to file a new issue or reach out to us on Discord if you have more questions.
