### ISSUE TITLE
I have no idea how to export rive2 animations

### ISSUE THREAD

**Issue by yeahse** [rive-app/rive-flutter#47]
Everything that worked on FlareActor doesn't work on rive2.
Obviously, I exported the animation, but there are only arbboard's wallpaper and the animation stopped.

I am really wandering. Is it still not supported in the beta version?

**Comment by luigi-rosso** [comment]
Seems like this might be a dupe of #51. Can you provide a sample file/source?

**Comment by luigi-rosso** [comment]
Please try ```rive: ^0.6.8``` to see if it helps with this issue. It fixes an issue where the last frame of a one-shot animation wasn't being drawn.
