### ISSUE TITLE
Is there any Listener for the Art board or Controller?

### ISSUE THREAD

**Issue by wangwailok** [rive-app/rive-flutter#50]
I am just switch from flare to Rive2(I am creating a new app and afraid abandon of flare)
but seems there is no such method or listener to listen the current frame or when the animation was finished.
Thanks

**Comment by mjohnsullivan** [comment]
I wrote an example to have a callback fro when an animation completes:

https://github.com/mjohnsullivan/rive-by-example/tree/main/flutter/f_06_callback_controller

Let me know if that helps.

**Comment by yeasin50** [comment]
also you check this [answer ](https://github.com/rive-app/rive-flutter/issues/75#issuecomment-817203881)

**Comment by mjohnsullivan** [comment]
Thanks for answering that issue :)
