### ISSUE TITLE
Some Animations rendering as static, not playing

### ISSUE THREAD

**Issue by niladri-paul** [rive-app/rive-flutter#51]
Some animations are coming as static, not rendering properly in flutter. Please help.

**Comment by meek2100** [comment]
I'm seeing this as well, I was on rive: ^0.6.4 and just switched to rive: ^0.6.7, but no improvement.

**Comment by luigi-rosso** [comment]
Did they used to play previously? Could either of you post a sample file/source?

**Comment by meek2100** [comment]
Here is the Rive 2 file that we were using to test with for our flutter app splash screen.
[rive_splashscreen_sample.zip](https://github.com/rive-app/rive-flutter/files/5973949/rive_splashscreen_sample.zip)

**Comment by luigi-rosso** [comment]
Hi @meek2100, thanks for the example. I loaded the file into our example player and it seems to play on mac, web, and iPhone. There is a condition where it'll sometimes stop on the wrong frame (it misses drawing the last frame). We're working on a fix for that but it should the animation is still technically being applied. I'll post here when that fix is live in case it's related. If a hot-restart helps, then this might be related.

In the meantime, can you provide the source for RiveSplashScreen? Even better, if you're able to, a complete full source repro would be really helpful!

**Comment by luigi-rosso** [comment]
Please try ```rive: ^0.6.8``` to see if it helps with this issue. It fixes an issue where the last frame of a one-shot animation wasn't being drawn.

**Comment by meek2100** [comment]
Tried 0.6.8 with no change. 

Here is the source for RiveSplashScreen:

`
class RiveSplashScreen extends StatefulWidget {
  final Function onSuccess;
  final String asset;
  final Color color;
  final String animationName;
  const RiveSplashScreen({
    Key key,
    @required this.onSuccess,
    @required this.asset,
    @required this.animationName,
    this.color,
  }) : super(key: key);
  @override
  _RiveSplashScreenState createState() => _RiveSplashScreenState();
}

class _RiveSplashScreenState extends State<RiveSplashScreen> {
  Artboard _riveArtboard;
  RiveAnimationController _controller;
  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      rootBundle.load(widget.asset).then(
        (data) async {
          final file = RiveFile();

          if (file.import(data)) {
            final artboard = file.mainArtboard;
            artboard.addController(_controller = SimpleAnimation('fluxstore'));
            setState(() {
              _riveArtboard = artboard;
            });
            _controller.isActiveChanged.addListener(() {
              if (!_controller.isActive) {
                Future.delayed(const Duration(seconds: 1))
                    .then((value) => widget.onSuccess());
              }
            });
          }
        },
      );
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: MediaQuery.of(context).size.width,
      height: MediaQuery.of(context).size.height,
      color: Colors.white,
      child: Center(
        child: _riveArtboard == null
            ? const SizedBox()
            : Rive(artboard: _riveArtboard),
      ),
    );
  }
}
`

**Comment by ab-ashagrie** [comment]
I'm facing the same problem https://github.com/meek2100 is facing. Have you found a solution ?

**Comment by mjohnsullivan** [comment]
I exported your Rive file in v7 format, and tried it with the latest runtime 0.7.18:

```dart
class SplashAnimation extends StatelessWidget {
  const SplashAnimation({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Simple Animation'),
      ),
      body: const Center(
        child: RiveAnimation.asset(
          'assets/splash.riv',
          fit: BoxFit.cover,
        ),
      ),
    );
  }
}
```

Here's an example showing how to detect when the animation has completed playing:

```dart
import 'package:flutter/material.dart';
import 'package:rive/rive.dart';

class SplashAnimation extends StatefulWidget {
  const SplashAnimation({Key? key}) : super(key: key);

  @override
  _SplashAnimationState createState() => _SplashAnimationState();
}

class _SplashAnimationState extends State<SplashAnimation> {
  late RiveAnimationController _controller;

  @override
  void initState() {
    super.initState();

    _controller = SimpleAnimation('fmksplash');
    _controller.isActiveChanged.addListener(_activeChanged);
  }

  void _activeChanged() {
    if (!_controller.isActive) {
      print('Animation complete');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Simple Animation'),
      ),
      body: Center(
        child: RiveAnimation.asset(
          'assets/splash.riv',
          fit: BoxFit.cover,
          controllers: [_controller],
        ),
      ),
    );
  }
}
```

**Comment by RohanUttamVeer** [comment]
it's not working in release mode
