### ISSUE TITLE
RiveRenderBox does not support Intrinsics

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rive-app/rive-flutter#54]
The Rive widget and render boxes currently do not support intrinsics at all.

When using `IntrinsicWidth` or `IntrinsicHeight` (for example), the Rive widget just returns `0` size (default fallback).  
More importantly, when relying on intrinsics (using custom render objects or ones that rely on it anyway), Rive does not work either.

You can [learn more about intrinsics here](https://api.flutter.dev/flutter/rendering/RenderBox-class.html#intrinsics-and-baselines).

---

This somewhat relates to #53, however, that is only an issue with the naming.

**Comment by luigi-rosso** [comment]
Thanks! The intention was for useIntrinsicSize to provide the actual intrinsic size as the dimensions of the artboard. Does it not work also when the useIntrinsicSize is set to true?

**Comment by creativecreatorormaybenot** [comment]
@luigi-rosso It does not work because the Flutter intrinsics contract needs to be explicitly supported.

I would open a PR to address this (should be very trivial) in ~1 hour. Does that work for you?

**Comment by luigi-rosso** [comment]
That'd be awesome, thanks @creativecreatorormaybenot!
