### ISSUE TITLE
Riv not animating

### ISSUE THREAD

**Issue by tajaouart** [rive-app/rive-flutter#56]
Hello,
The Riv object is not animating, it only shows tge first frame (displayed as an image), i tried the example in the [rive package](https://pub.dev/packages/rive) but not working, i changed the object by getting examples from the website(riv) and changed the  SimpleAnimation name with no success on both web(chrome) and Android,

 Flutter (Channel beta, 1.26.0-17.4.pre, on Microsoft Windows [version 10.0.18363.1316], locale fr-FR)
    • Flutter version 1.26.0-17.4.pre at C:\Users\aksel\AppData\Local\Android\flutter
    • Framework revision 48c9d3e0e1 (2 days ago), 2021-02-10 11:46:09 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\\Users\\aksel\\AppData\\Local\\Android\\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\aksel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\aksel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!

**Comment by JaffaKetchup** [comment]
I appear to have this same issue.

**Comment by devandrefernandes** [comment]
I appear to have this same issue.

**Comment by devandrefernandes** [comment]
It worked for me:

I changed the name of the animation inside the rive editor and inserted the same name in SimpleAnimation.

`_controller = SimpleAnimation('loading');`

![Captura de tela de 2021-02-14 13-46-03](https://user-images.githubusercontent.com/7664151/107883035-20a47f80-6ecb-11eb-9bb8-cd835bcc0feb.png)

I downloaded it again, imported it into the flutter and it worked perfectly.

**Comment by Puspharaj** [comment]
It won't work in release

**Comment by luigi-rosso** [comment]
This may be related to #51. We haven't figured out why some devices seem to not be playing animations back. All our local test files work in both debug and release. It may be related to Flutter verion, we're doing further testing.

**Comment by devandrefernandes** [comment]
> It won't work in release

I created an apk release and installed it on my phone, it worked perfectly.

When can it not work?

I can test to confirm whether it works or not.

**Comment by luigi-rosso** [comment]
Doesn't seem to be version related (unless something changed in the latest beta). The example plays back in ```Flutter 1.24.0-10.2.pre • channel beta``` when running with ```flutter run -dchrome``` and ```flutter run -dchrome --release```. 

Perhaps this is an issue with specific files. Could you provide the exact file and animation you are trying to play?

**Comment by luigi-rosso** [comment]
Please try ```rive: ^0.6.8``` to see if it helps with this issue. It fixes an issue where the last frame of a one-shot animation wasn't being drawn.

**Comment by Puspharaj** [comment]
I meant flutter web. Running local instance works, but when I'm deploying
to the firebase hosting. It doesn't show anything just a blank page.

**Comment by tajaouart** [comment]
> It won't work in release

indeed, it does not work on depolyment, i think there isn't an opened issue, i'll create one !

i sloved the current issue thanks to the answer of  @devandrefernandes

**Comment by mjohnsullivan** [comment]
There's a few different questions in this issue, but to focus on web playback in deployment:

As an experiment, I built the example app in this repo with the latest Flutter release (2.0.1) for the web and deployed it here:

https://cdn.rive.app/flutter_web_test/index.html

It seems to be running fine. Are folk still seeing issues with playing rive animations in Flutter web when deploying?

**Comment by mjohnsullivan** [comment]
Closing this for the moment, but if any of these issues still exist, please reopen and we'll continue to assist.

**Comment by mravinshu** [comment]
I am still facing this issue can anyone assist me

**Comment by mdrashedbinkuddus** [comment]
Hi there,
Facing the same problem here. I am using `rive: ^0.10.3` my file structure is assets/rive/empty.riv

I'm using it on showDialog

`showDialog(context: context,
builder: (context) => AlertDialog( title: const Center(
                                    child: Text('Nothing here yet')),
                                content: SizedBox(
                                  width: screenWidth * 300,
                                  height: screenHeight * 300,
                                  child: const RiveAnimation.asset(
                                    'rive/empty.riv',
                                    artboard: 'New Artboard',
                                    animations: ['one'],
                                    fit: BoxFit.contain,
                                  ),
                                ),
                              ),
                            );`

Working fine in my local dev but not in firebase hosting. Any solution?
