### ISSUE TITLE
Flutter Web Rive not working anymore!

### ISSUE THREAD

**Issue by Puspharaj** [rive-app/rive-flutter#59]
rive: 0.6.8

with latest flutter pre build versions are not compatible with rive, just showing blank page. Please fix it asap. 

Thanks!

**Comment by Puspharaj** [comment]
I wonder how the rive 2 is working with rive files?. Rive2 was entirely redesigned in flutter and i guess it should work with the rive files, and it works. 

So im hosting the site in firebase. Is it the cause for not showing rive animation, maybe the tree shaking would cause the blank page?.

**Comment by mjohnsullivan** [comment]
I tested Flutter web today with the example app in this repo on Flutter 2.0.1 and deployed the build here:

https://cdn.rive.app/flutter_web_test/index.html

It appears to be working on both desktop and mobile. Are you still seeing issues?

**Comment by Puspharaj** [comment]
Thanks issue seems to be resolved. But let me check my side too.

**Comment by mjohnsullivan** [comment]
Let us know if it works so we can assist if not.

**Comment by Puspharaj** [comment]
Sure! will close the issue now, but will open it again if further issue pops up.
