### ISSUE TITLE
Rive not working on deployment

### ISSUE THREAD

**Issue by tajaouart** [rive-app/rive-flutter#60]
Hello,
I deployed my Flutter app to Firebase Hosting, but the Rive widget does not appear in the page, as if there was no Rive widget, the naviigator's consol shows no indications.
Localy it works fine,

dependencies:
  rive: ^0.6.7
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0

Flutter (Channel beta, 1.26.0-17.4.pre, on Microsoft Windows [version 10.0.18363.1316], locale fr-FR)
• Flutter version 1.26.0-17.4.pre at C:\Users\aksel\AppData\Local\Android\flutter
• Framework revision 48c9d3e0e1 (2 days ago), 2021-02-10 11:46:09 -0800
• Engine revision 2c527d6c7e
• Dart version 2.12.0 (build 2.12.0-259.8.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at C:\Users\aksel\AppData\Local\Android\Sdk
• Platform android-30, build-tools 30.0.3
• ANDROID_HOME = C:\Users\aksel\AppData\Local\Android\Sdk
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
• VS Code at C:\Users\aksel\AppData\Local\Programs\Microsoft VS Code
• Flutter extension can be installed from:
https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
• Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!

**Comment by Puspharaj** [comment]
Same issue here!, How the Rive main website running with the rive files? The Rive2 website from Flutter WEB. How come the rive animation works on there website?. Interesting.

**Comment by Puspharaj** [comment]
Bump, is anyone there?.... Nobody responded after 8 days.

**Comment by Puspharaj** [comment]
Nice

**Comment by Will-Swain-Sprout** [comment]
@tajaouart what was the resolution in the end? I'm also having the same problem.

**Comment by meniMaatuf** [comment]
hi, is there any resolution? i have the same problem with the latest version 0.7.12

**Comment by meniMaatuf** [comment]
@tajaouart do you have the resolution?

**Comment by dtrbinh** [comment]
@Shiba-Kar can u share code block to read file .riv?
In my case, the problem was on there.
When debug, we didnt need "assets/", like this:
`rootBundle.load('rive/shock_deer_animation.riv')`

But when deploy, we need add "assets/", like this:
`rootBundle.load('assets/rive/shock_deer_animation.riv')`

Let's test it with debug and `firebase serve`. 
This problem same with file .json, etc read by `rootBundle.load()`
Good luck.

**Comment by TiagoMLeite** [comment]
This solved the problem for me. Also when loading Image assets the fix was the same: 
Image..asset("/my_image") will work on run but not on deployed version
Fix: Image.asset("assets/my_image")
Thank you very much!!

> @Shiba-Kar can u share code block to read file .riv? In my case, the problem was on there. When debug, we didnt need "assets/", like this: `rootBundle.load('rive/shock_deer_animation.riv')`
> 
> But when deploy, we need add "assets/", like this: `rootBundle.load('assets/rive/shock_deer_animation.riv')`
> 
> Let's test it with debug and `firebase serve`. Same problem with file .json, etc read by `rootBundle.load()` Good luck.

**Comment by mdrashedbinkuddus** [comment]
Same problem here

I tried to change the path but nothing seems to work. I am using rive asset

**Comment by NashIlli** [comment]
Same problem!
