### ISSUE TITLE
Rive doesn't play animation

### ISSUE THREAD

**Issue by andrvm** [rive-app/rive-flutter#61]
rive: 0.6.8
flutter channel stable, 1.22.3, on Linux.

I follow some guides ([one](https://pub.dev/packages/rive), [two](https://blog.rive.app/rives-flutter-runtime-part-1/)) to implement rive package with my flutter application. I follow exactly the way as they recommend but whatever file I pick up the file isn't being played by the app.
What is wrong with it or it might be an issue?

Thanks!

**Comment by mjohnsullivan** [comment]
Is this still an issue for you on the latest Flutter stable?

**Comment by andrvm** [comment]
> do you set the correct animation name when create `SimpleAnimation`?
> 
> ```
> artboard.addController(_controller = SimpleAnimation('idle'));
> ```

SimpleAnimation('loading') solved the issue.

**Comment by andrvm** [comment]
> Is this still an issue for you on the latest Flutter stable?

No.
