### ISSUE TITLE
Container Box Radius Not Applying to Animation

### ISSUE THREAD

**Issue by apteryxlabs** [rive-app/rive-flutter#66]
Hi all,

I'd like to clip the corners of my rive animation so as to round the corners. To do so I did the following (all other code follows the example in your [blog](https://blog.rive.app/rives-flutter-runtime-part-1/)):

```
/// Show the rive file, when loaded
  @override
  Widget build(BuildContext context) {
    return _artboard != null
        ? Container(
            decoration: BoxDecoration(
                border: Border.all(
                  color: Colors.red,
                  width: 5,
                ),
                borderRadius: BorderRadius.circular(100)),
            child: Rive(
              artboard: _artboard,
              fit: BoxFit.cover,
            ),
          )
        : Container();
  }
```

I expected the Container to contstrain the edges of the Rive animation; instead, the edges of the (square) animation poke through like so:
<img width="340" alt="asdfasdfasdf" src="https://user-images.githubusercontent.com/65966807/111226594-be1ccd00-85b7-11eb-81e8-c7188c677841.png">

Am I missing something? Would love the option to clip/mask animations from within flutter!

**Comment by apteryxlabs** [comment]
Any updates on this?

**Comment by luigi-rosso** [comment]
The contain doesn't explicitly clip its contents, try wrapping the Rive widget with a ClipRRect widget: https://api.flutter.dev/flutter/widgets/ClipRRect-class.html
