### ISSUE TITLE
How to precache/preload Rive (.riv) animations?

### ISSUE THREAD

**Issue by carman247** [rive-app/rive-flutter#68]
I've found some info on how to preload Flare (.flr) animations but I can't find any info on how to export an animation from Rive as Flare.

Would be great if there was an example for either of these.

Many thanks

**Comment by roflan94** [comment]
Yes same issue for me i'd like to precache .riv animations but couldn't find a way to do that .

**Comment by roflan94** [comment]
@luigi-rosso Please if there is any updates tell us , Thank you!

**Comment by luigi-rosso** [comment]
We don't have an explicit API to do this yet. 

One easy way to implement a similar concept is using a Flutter InheritedWidget to propagate your loaded RiveFiles to the rest of the widget hierarchy that needs it.

**Comment by fredgrott** [comment]
I have an observation,

If riv files are considered text blobs we already have it cacheable via assetbundel right?

**Comment by amirbennasr-smic** [comment]
> I have an observation,
> 
> If riv files are considered text blobs we already have it cacheable via assetbundel right?

I didn't think about this would try it 😁

**Comment by marcolatellafrias** [comment]
@HayesGordon  Is there an update on when this could be shipped? Thank you!

**Comment by HayesGordon** [comment]
We have documentation showing how to do this: https://rive.app/community/doc/caching-a-rive-file/docWIF4v2ppr

In conjunction with [asset loading](https://rive.app/community/doc/loading-assets/doct4wVHGPgC), you can have full control on caching the .riv file and it's assets.
