### ISSUE TITLE
rive v0.6.8 is incompatible with build_runner >=1.12.0

### ISSUE THREAD

**Issue by brizaldi** [rive-app/rive-flutter#69]
```
Because build_runner >=1.12.0 depends on graphs ^1.0.0 and rive 0.6.8 depends on graphs ^0.2.0, build_runner >=1.12.0 is incompatible with rive 0.6.8.
```

I'm using both rive and build_runner in my project, but the latest version of rive did not use the same version of graphs as build_runner. Is it possible to update this?

Thank you in advance.

**Comment by mjohnsullivan** [comment]
We're in the process of updating the library for NNBD, and the graphs dependency is updating to 1.0.0.

It'll land shortly on master, but you can try the nnbd branch if you'd like to see it sooner.

**Comment by fredgrott** [comment]
note, _ ran into similar issue and resolved it by updating to 2.0.2 on build_runner you might want to try that fix

**Comment by mjohnsullivan** [comment]
This should be resolved in the latest releases of the library; try v0.7.9 and let us know if you're still having issues.

**Comment by brizaldi** [comment]
Updating rive to latest version [v0.7.9] solved this issue
