### ISSUE TITLE
Exception on the NNBD beta

### ISSUE THREAD

**Issue by inceptusp** [rive-app/rive-flutter#71]
When I try to load my `.riv` file with the new `rive: ^0.7.0-nullsafety.0` I get the following message:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following UnsupportedError was thrown building FutureBuilder<ByteData>(dirty, state: _FutureBuilderState<ByteData>#c1468):
Unsupported operation: Unsupported property key 1. A new runtime is likely necessary to play this file.

The relevant error-causing widget was
FutureBuilder<ByteData>
package:rive_test/main.dart:83
When the exception was thrown, this was the stack
#0      _skipProperty                                                          package:rive/src/rive_file.dart:63
#1      _readRuntimeObject                                                     package:rive/src/rive_file.dart:49
#2      new RiveFile._                                                         package:rive/src/rive_file.dart:103
#3      new RiveFile.import                                                    package:rive/src/rive_file.dart:217
#4      _MyHomePageState.build.<anonymous closure>                             package:rive_test/main.dart:87
...
════════════════════════════════════════════════════════════════════════════════
```

I think it is related to this statement from the changelog: `New binary format 7.0 with improved flexibility which is not compatible with 6.0 files. The Rive editor will be able to export both format 6.0 and 7.0, but please note that 6.0 is now deprecated and all new improvements and bug fixes to the format will be done on 7.0.` but this means that the "old" format is incompatible with this version? And, if so, how can I get a new format from the editor?

**Comment by luigi-rosso** [comment]
Yes! The new editor isn't released yet (should be any day now) so please keep using the non-nnbd version until the new editor is available. You'll have an option like the one below to export the newer version which is compatible with >0.7.0 runtimes:
![image](https://user-images.githubusercontent.com/454182/113082140-c3207580-918e-11eb-9d13-92a82efd207c.png)

**Comment by inceptusp** [comment]
Oh, ok... I'll wait then... I can't use the old version on this project 'cause it is already migrated to NNBD...
Thx 😊
