### ISSUE TITLE
Can't import file from url

### ISSUE THREAD

**Issue by YeomDongUk** [rive-app/rive-flutter#72]
``` dart
Future<RiveFile> _fileFromImageUrl() async {
    HttpClient client = HttpClient();
    HttpClientRequest request = await client.getUrl(Uri.parse(
        "https://res.cloudinary.com/color-project/raw/upload/v1617085445/color/challenge/challenge_animation/rocket_movlqn.riv"
        // _challengeGroup.challenges[0].animationUrl
        ));
    HttpClientResponse response = await request.close();
    var data = await consolidateHttpClientResponseBytes(response);
    var file = RiveFile.import(ByteData.view(data.buffer));
    print(file);
    return file; 
}
```
I want to import file from web, not using rootBundle.
I try to import with http, dio, httpClient but I can't .

plz help me

![스크린샷 2021-03-30 오후 3 29 35](https://user-images.githubusercontent.com/40842475/112943679-c0ad2400-916c-11eb-8108-0b8232d23681.png)

Above screen shot is the result of the error

**Comment by mjohnsullivan** [comment]
There's new support for loading Rive files over HTTP; have a look at the RiveAnimation widget: https://help.rive.app/runtimes/quick-start#1-add-the-rive-package-dependency

**Comment by mjohnsullivan** [comment]
It also looks like you may be using an older version of the runtime. Please ensure that you're using the latest v0.7 of the runtime, and that your Rive files have been exported from the editor in v7:

![Screen Shot 2021-06-14 at 3 52 33 PM](https://user-images.githubusercontent.com/102488/121969175-94934f00-cd28-11eb-9b4b-ae04d264da70.png)
