### ISSUE TITLE
Update README example for NNBD

### ISSUE THREAD

**Issue by maxlapides** [rive-app/rive-flutter#73]
I noticed there's a breaking change in the null safe version of this package. This chunk of code in the README should be updated with the latest best practice:

```dart
final file = RiveFile();

// Load the RiveFile from the binary data.
if (file.import(data)) { ... }
```

**Comment by luigi-rosso** [comment]
Thanks, yes we definitely need to do that! You also can't export v7 files yet so you won't be able to use the null safe version quite yet.

**Comment by maxlapides** [comment]
I learned that one the hard way 😂

**Comment by luigi-rosso** [comment]
Sorry about that, should've added that to the changelog (big oops)!!

**Comment by MarcinusX** [comment]
Can we use null safe version now?

**Comment by mjohnsullivan** [comment]
Yep, the package is null safe.
