### ISSUE TITLE
Only runs once

### ISSUE THREAD

**Issue by idkq** [rive-app/rive-flutter#74]
My riv is only running once after build. When I toggle:

```dart
setState(() => _controller.isActive = !_controller.isActive);
```

nothing happens. I can se from the console:

```
flutter: Animation started playing
flutter: Animation stopped playing
```

That is starting and stopping almost at the same time. Do I need to rewind it or something?

**Comment by luigi-rosso** [comment]
The SimpleAnimation will only play the animation once if it's not looping. A few ways to do this:

- Make your own controller to do this by resetting the time on the animationInstance inside of SimpleController.
- Remove the SimpleAnimation and re-add a new one once it's complete.
- Wait for the StateMachine which releases soon which will let you set inputs to control animation states.

**Comment by idkq** [comment]
Awesome! Maybe add this paragraph to the docs? Very helpful!
