### ISSUE TITLE
How do I start new animation after one finishes

### ISSUE THREAD

**Issue by jay-iamin** [rive-app/rive-flutter#75]
I have 2 animations, named "initial" and "looper", "initial" runs only once and "looper" runs in a loop . How do I start "looper" animation when "initial" ends. 

Thanks for your help

**Comment by yeasin50** [comment]
on State decleare 2 Simple animation;
```
SimpleAnimation initial=  SimpleAnimation('initial');
SimpleAnimation looper=  SimpleAnimation('looper');
```
on **initState**  add `initial`  at controller. 

inside initState add Timer to check the initial state like :
```
Timer(Duration(milliseconds: 400), () {
      initial.isActiveChanged.addListener(() {
        if (initial.isActive == false) {
          log("initial anim ended ✌");
          SchedulerBinding.instance.addPostFrameCallback((_) {
            ///  remove  initial animation and add looper 
             _riveArtboard.artboard.removeController(initial);
             _riveArtboard.artboard.addController(looper);

          });

```
also you can check my code [here ](https://github.com/yeasin50/Shaheed_minar/blob/77131a457f6c7eaabd0c664e111a0474fb5841c4/lib/rive/shaheed_minar.dart#L65-L76)

**Comment by yeasin50** [comment]
on State decleare 2 Simple animation;
```
SimpleAnimation initial=  SimpleAnimation('initial');
SimpleAnimation looper=  SimpleAnimation('looper');
```
on **initState**  add `initial`  at controller. 

inside initState add Timer to check animation status like :
```
Timer(Duration(milliseconds: 400), () {
      initial.isActiveChanged.addListener(() {
        if (initial.isActive == false) {
          log("initial anim ended ✌");
          SchedulerBinding.instance.addPostFrameCallback((_) {
            ///  `remove  initial animation and add looper `
             _riveArtboard.artboard.removeController(initial);
             _riveArtboard.artboard.addController(looper);

          });

```
also you can check my code [here ](https://github.com/yeasin50/Shaheed_minar/blob/77131a457f6c7eaabd0c664e111a0474fb5841c4/lib/rive/shaheed_minar.dart#L65-L76)

**Comment by mjohnsullivan** [comment]
We've posted an example of how to use the new `RiveAnimation` widget with one-shot animations, which shows how to listen for when a one-shot completes: https://help.rive.app/runtimes/playback#repeatedly-playing-a-one-shot-animation
