### ISSUE TITLE
Using Rive State Machine Trigger in Flutter

### ISSUE THREAD

**Issue by elmdecoste** [rive-app/rive-flutter#76]
Hey y'all, I'm looking through the code example for flutter and state machines, but I haven't seen a way to use triggers within the sdk

The example here (https://github.com/rive-app/rive-flutter/blob/master/example/lib/example_state_machine.dart) shows how to use boolean inputs but not triggers

**Comment by luigi-rosso** [comment]
You're right, we're missing that! We're doing a pretty big cleanup of the StateMachine API early next week to avoid having to import from src folder files, adding triggers, and fixing a few other loose ends.

**Comment by jorgefspereira** [comment]
any update on this?

**Comment by luigi-rosso** [comment]
Yes! We made one and then I never updated this thread. Take a look here: https://github.com/rive-app/rive-flutter/blob/a832d55f07704c3917ac70efd1a4373b4c46349f/example/lib/little_machine.dart#L40
