### ISSUE TITLE
NoSuchMethodError: The method '/' was called on null.

### ISSUE THREAD

**Issue by quentingosset** [rive-app/rive-flutter#78]
Hello, I have a problem when I copy / paste the example from your documentation here: https://help.rive.app/runtimes/example I get an error "Unhandled Exception: NoSuchMethodError: The method '/' was called on null.
I use version 0.6.8 of Rive, I downloaded a file from the community (https://rive.app/community/38-heart/) in version 6 and the file is well defined in the YAML file.
Here is the error is the piece of code (the error is in the "if (file.import(bytes))"):

````
class _IntroWelcomePageState extends State<IntroWelcomePage> {
  var _scaffoldKey = new GlobalKey<ScaffoldState>();
  final riveFileName = 'assets/heart.riv';
  Artboard _artboard;

  @override
  void initState() {
    _loadRiveFile();
    super.initState();
  }

  // loads a Rive file
  void _loadRiveFile() async {
    final bytes = await rootBundle.load(riveFileName);
    final file = RiveFile();

    if (file.import(bytes)) {
      // Select an animation by its name
      setState(() => _artboard = file.mainArtboard
        ..addController(
          SimpleAnimation('idle'),
        ));
    }
  }
````

````
E/flutter (11419): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '/' was called on null.
E/flutter (11419): Receiver: null
E/flutter (11419): Tried calling: /(60)
E/flutter (11419): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (11419): #1      KeyFrame.computeSeconds (package:rive/src/rive_core/animation/keyframe.dart:31:28)
E/flutter (11419): #2      RiveFile.import (package:rive/src/rive_file.dart:134:26)
E/flutter (11419): #3      _IntroWelcomePageState._loadRiveFile (package:kalium_wallet_flutter/ui/intro/intro_welcome.dart:37:14)
E/flutter (11419): <asynchronous suspension>
E/flutter (11419): 
Restarted application in 1 059ms.
```
`

**Comment by roeniss** [comment]
I have same issue here.

After rive editor has two download options, v6 version .riv file doesn't work at all.

Is this problem of rive?

![image](https://user-images.githubusercontent.com/26613280/113464646-3f55da00-9469-11eb-8a9d-34d6e571ef9a.png)

**Comment by roeniss** [comment]
just quick fix: upgrade library to 0.7.0, then download v7

**Comment by quentingosset** [comment]
I can’t use 0.7.0 actually I have a lot of dependancie bugged if I use 0.7.0 :/

**Comment by specOper99** [comment]
Same Here :)
Also can't update to 0.7.0

**Comment by alexbhandari** [comment]
Same issues here

**Comment by luigi-rosso** [comment]
Thanks for the report! It looks like the file isn't exporting valid keyframe times from the errors above. Looking into this shortly!

**Comment by luigi-rosso** [comment]
I think I see how this could've happened. We made the new exporter smarter so that it doesn't export "default" values. Unfortunately, those defaults were different for V6 so the V6 exporter needs to force export default values too otherwise they'll result as null values in the old runtimes. Great catch, sorry for the hassle. We should have a fix later today.

**Comment by luigi-rosso** [comment]
That was it, we'll have a fix shortly, meantime here's a valid v6 heart you can use with the v6 runtimes! 
[heart.riv.zip](https://github.com/rive-app/rive-flutter/files/6253259/heart.riv.zip)

**Comment by quentingosset** [comment]
I'm back on Monday I'll test on Monday and let you know :).

Thanks for the fix !

**Comment by specOper99** [comment]
> That was it, we'll have a fix shortly, meantime here's a valid v6 heart you can use with the v6 runtimes!
> [heart.riv.zip](https://github.com/rive-app/rive-flutter/files/6253259/heart.riv.zip)

Sorry to tell you but the problem I have is with my own files, so I have to wait only
Thank you for the response and hope the fixing operation will be easy and fast

**Comment by luigi-rosso** [comment]
Sorry the issue wasn't meant to be closed yet, it'll be closed once the build is live in the editor. I'll message here when that's the case.

**Comment by luigi-rosso** [comment]
Please try re-exporting v6 files from the latest editor, which is version 0.6.3.
![image](https://user-images.githubusercontent.com/454182/113494034-9d021a80-9499-11eb-8bd8-4944ff7d5d1b.png)

**Comment by specOper99** [comment]
> The issue should now be fixed as the latest editor is live. Please try re-exporting v6 files from the latest editor, which is version 0.6.3.
> ![image](https://user-images.githubusercontent.com/454182/113494034-9d021a80-9499-11eb-8bd8-4944ff7d5d1b.png)

Thank you, it was fixed 🙏🏻
Really appreciate everything ❤️

**Comment by quentingosset** [comment]
@luigi-rosso yes it's fixed 🥇  i close the issue.
