### ISSUE TITLE
Flutter: How to make the height of the PageView depend on its child?

### ISSUE THREAD

**Issue by RAHEYO** [rive-app/rive-flutter#79]
**Question:**

In flutter, if you don't set a fixed height or aspect ratio to PageView, it will give you an error that says "... has a unbounded", but what if I want the height or aspect ratio be dynamic and change over time depends on the child?

**Detail:**

In Instagram, the height of your post is dynamic, it depends on your image, and this is also the effect I want to achieve, and here's my code:

       Column: (
        children: [
         AspectRatio(
            aspectRatio: 1 / 1,
            child: PageView.builder(
                pageSnapping: true,
                itemBuilder: (context, index) {
                  if (<isAVideo>) {
                     return VideoWidget();
                  } else {
                     return ImageWidget();
                  }
                },
            ),
          ),
        ],
     ),
But it does not work if I take the aspect ratio away. Because I think some geniuses on StackOverflow can solve my issue, so that's the reason why I posted this question~ @_@

I had also tried to wrap the PageView inside a ConstraintBox, and give a boxConstraint with a max height, and the result is that the UI automatically follow the maxHeight by default, but not the min height that I gave to it, **_so if there is way to let the widget follow the minHeight by default, and only reach the maxHeight when needed, this problem can also be solved, I think it's another good idea to solve the this question~_**

**Comment by tsinis** [comment]
Hey @RAHEYO, sorry to say, but I think you are in the wrong repository. This is Flutter specific question and surely does not belong to the Issues section of the Rive repo...

**Comment by RAHEYO** [comment]
Yeah, you're white.
