### ISSUE TITLE
Change colour of animation

### ISSUE THREAD

**Issue by theweiweiway** [rive-app/rive-flutter#80]
Hi! Before when I used Flare, there was a `color` property on the `FlareActor` widget that allowed me to change the colour of the animation. 

Can I still do this with the `Rive` component? 

Thanks

**Comment by fredgrott** [comment]
no, you have to find out the names of components and then color them

**Comment by luigi-rosso** [comment]
We don't currently support this, but if you still need it, please suggest it on our roadmap! https://feedback.rive.app/roadmap

**Comment by zerogravityent** [comment]
This works for me:
```
Color color = Colors.red;
artboard.forEachComponent((c) {
      if (c.coreType == 18) {
        SolidColorBase solidColorBase = c;
        solidColorBase.colorValue = color.value;
      }
    });
```
