### ISSUE TITLE
Control animation with GestureDetector

### ISSUE THREAD

**Issue by MatteoAntolini** [rive-app/rive-flutter#83]
I created a sort of bottom sheet with rive and I can manage ontap animations and I would like to control the current % of animation with the `DragUpdateDetails`

**Comment by mjohnsullivan** [comment]
Best way to currently handle that currently is to use a state machine with number inputs and programmatically control the value through that.

There's a few examples of using state machines in the repo examples, and we're updating our help center with docs now. We'll have more examples with number values shortly as well.

https://help.rive.app/runtimes/state-machines
