### ISSUE TITLE
Documentation out of date regarding creating RiveFile

### ISSUE THREAD

**Issue by ChristianKleineidam** [rive-app/rive-flutter#87]
At https://blog.rive.app/rives-flutter-runtime-part-1/ and https://blog.rive.app/pull-to-refresh-flutter/ the Rive documentation suggest to create a RiveFile via calling a default constructor and then loading the content:

   ```
final file = RiveFile();

   if (file.import(bytes)) {
     setState(() => _artboard = file.mainArtboard
       ..addController(
         SimpleAnimation('idle'),
       ));
   }

```
It seems like this changed and now has to be:

    final file = RiveFile.import(bytes);

    setState(() => _artboard = file.mainArtboard
      ..addController(
        SimpleAnimation('idle'),
      ));

**Comment by maxlapides** [comment]
Duplicate https://github.com/rive-app/rive-flutter/issues/73

**Comment by fredgrott** [comment]
yes and the if conditional should be bytes.buffer.isFinite as file.import does not exist!

**Comment by mjohnsullivan** [comment]
These blog posts are very out of date and we're in the process of updating our dev docs and blog posts. We'll get this corrected shortly.

**Comment by mjohnsullivan** [comment]
We've updated the examples in the Gtihub repo: https://github.com/rive-app/rive-flutter/tree/master/example

We've also started to flesh out our developer documentation in our help center, which has the latest Flutter docs: https://help.rive.app/runtimes/quick-start#1-add-the-rive-package-dependency

**Comment by mjohnsullivan** [comment]
Blog post's been rewritten: https://blog.rive.app/rives-flutter-runtime/
