### ISSUE TITLE
Will Rive support human readable files like Flare did?

### ISSUE THREAD

**Issue by ChristianKleineidam** [rive-app/rive-flutter#88]
Human readable files give the potential when dealing with creating a large number of assets to automate the task. Will Rive support that again or provide other ways to automate adding the same animation to many different files?

**Comment by mjohnsullivan** [comment]
We're not working on a json-like version of Rive's file format at the moment. We readers and writers for our binary format, though haven't put a developer-friendly api on top of them, though that's possible.

The biggest headache manually copying animations between files via a method like this would be tying the ids of the animating properties two the animation, as they will in all likelihood different between Rive files.
