### ISSUE TITLE
How do I know where on the screen a ContainerComponent is placed?

### ISSUE THREAD

**Issue by ChristianKleineidam** [rive-app/rive-flutter#89]
When my user clicks on the screen I want to be able to calculate the distance between the point that the user clicks on the screen and a ContainerComponent which a specific name. By iterating through artboard.children and the children on lower levels I successfully find the ContainerComponent I care about.

I access it's path via component.fillPath

If I however draw the path to the screen it's not where the element is. If I draw it directly I get:
![grafik](https://user-images.githubusercontent.com/5765379/115923728-f4831d00-a47e-11eb-87da-12f67df680f0.png)

If I shift the path by Offset(200,200) I get:
![grafik](https://user-images.githubusercontent.com/5765379/115923668-dcab9900-a47e-11eb-8aa3-94cc5723c7b4.png)

This means that the path is not only shifted in location but also scaled up. How do I determine the true location of the border of the ContainerComponent (like a Shape)?

**Comment by HayesGordon** [comment]
Hey @ChristianKleineidam 

You can find a component on an artboard (by it's name and type) and get its position. Sample code:

```dart
class SimpleTest extends StatefulWidget {
  const SimpleTest({super.key});

  @override
  State<SimpleTest> createState() => _SimpleTestState();
}

class _SimpleTestState extends State<SimpleTest> {
  late Artboard artboard;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          RiveAnimation.asset(
            'assets/findme.riv',
            useArtboardSize: true,
            stateMachines: const ['State Machine 1'],
            onInit: (a) {
              artboard = a;
            },
          ),
          ElevatedButton(
            onPressed: () {
              artboard.forEachComponent((p0) {
                // loop through all components and see what is available
                print(p0);
              });
              // find a component by type and name and get it's translation
              final shape = artboard.component<Shape>("findme");
              print(shape?.worldTranslation);
            },
            child: const Text('Click me'),
          )
        ],
      ),
    );
  }
}
```

It's important though that if you want a component to be discoverable by it's name, you need to manually enter the name in the Rive editor - else it will not be included in the exported .riv (to save space).

<img width="542" alt="CleanShot 2023-08-10 at 15 04 47@2x" src="https://github.com/rive-app/rive-flutter/assets/13705472/e0c89c56-4004-4fcc-98f9-22441b163328">

In the image above I entered the name "findme" on the shape. The `forEachComponent` will be helpful to discover what is on an artboard and what the correct type is.

You can also take a look at a more complex example if you want to tap into the render loop and get the position each frame. See our docs:
- https://help.rive.app/runtimes/overview/flutter/custom-rive-renderobject
- https://help.rive.app/runtimes/overview/flutter/custom-painter

Closing this issue.
