### ISSUE TITLE
Enrich flutter package documentation

### ISSUE THREAD

**Issue by piyushchauhan** [rive-app/rive-flutter#9]
As a developer I look in to the docs of any package and its example to understand the usage of it. I think there should be a richer documentation so that developers are confident to use this package in their apps. I could not find anything as documentation on [pub.dev](https://pub.dev/packages/rive)

**Comment by luigi-rosso** [comment]
Hi @piyushchauhan,

This is an early preview of the Rive 2 runtimes. They are very much a work in progress. The Rive 2 tool is not generally available yet. Adding documentation to this package is a big part of it becoming generally available.

If you're looking for the Rive (used to be named Flare) Flutter package, you can find it here: https://github.com/2d-inc/flare-flutter

Thanks for filing!

**Comment by mjohnsullivan** [comment]
We've written a blog post detailing how to use the plugin: https://blog.rive.app/rives-flutter-runtime-part-1/

**Comment by mjohnsullivan** [comment]
Added blog post link to the README; more to come in the near future.
